"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:16

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import ConfigDict

from .basic_types import MeasureType

__NAMESPACE__ = "http://www.opengis.net/gml/3.2"


class AngleType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class AreaType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class GridLengthType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class LengthType(MeasureType):
    """
    This is a prototypical definition for a specific measure type defined as a vacuous extension (i.e. aliases) of
    gml:MeasureType.

    In this case, the content model supports the description of a length (or distance) quantity, with its units. The
    unit of measure referenced by uom shall be suitable for a length, such as metres or feet.
    """

    model_config = ConfigDict(defer_build=True)


class ScaleType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class SpeedType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class TimeType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class VolumeType(MeasureType):
    pass
    model_config = ConfigDict(defer_build=True)


class Measure(MeasureType):
    """
    The value of a physical quantity, together with its unit.
    """

    class Meta:
        name = "measure"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class Angle(AngleType):
    """
    The gml:angle property element is used to record the value of an angle quantity as a single number, with its
    units.
    """

    class Meta:
        name = "angle"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
