"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:16

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from ........xlink import (
    ActuateType,
    ShowType,
    TypeType,
)
from .basic_types import NilReasonEnumerationValue
from .gml_base import ReferenceType
from .temporal import (
    AbstractTimeComplexType,
    AbstractTimePrimitiveType,
    TimeInstantPropertyType,
    TimePeriodPropertyType,
)

__NAMESPACE__ = "http://www.opengis.net/gml/3.2"


class AbstractTimeTopologyPrimitiveType(AbstractTimePrimitiveType):
    model_config = ConfigDict(defer_build=True)
    complex: None | ReferenceType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class AbstractTimeTopologyPrimitive(AbstractTimeTopologyPrimitiveType):
    """
    gml:TimeTopologyPrimitive acts as the head of a substitution group for topological temporal primitives.

    Temporal topology primitives shall imply the ordering information between features or feature properties. The
    temporal connection of features can be examined if they have temporal topology primitives as values of their
    properties. Usually, an instantaneous feature associates with a time node, and a static feature associates with
    a time edge. A feature with both modes associates with the temporal topology primitive: a supertype of time
    nodes and time edges. A topological primitive is always connected to one or more other topological primitives,
    and is, therefore, always a member of a topological complex. In a GML instance, this will often be indicated by
    the primitives being described by elements that are descendents of an element describing a complex. However, in
    order to support the case where a temporal topological primitive is described in another context, the optional
    complex property is provided, which carries a reference to the parent temporal topological complex.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TimeNodeType(AbstractTimeTopologyPrimitiveType):
    model_config = ConfigDict(defer_build=True)
    previous_edge: list[TimeEdgePropertyType] = field(
        default_factory=list,
        metadata={
            "name": "previousEdge",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    next_edge: list[TimeEdgePropertyType] = field(
        default_factory=list,
        metadata={
            "name": "nextEdge",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    position: None | TimeInstantPropertyType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class TimeNode(TimeNodeType):
    """
    A time node is a zero-dimensional topological primitive that represents an identifiable node in time (it is
    equivalent to a point in space).

    A node may act as the termination or initiation of any number of time edges. A time node may be realised as a
    geometry, its position, whose value is a time instant.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TimeNodePropertyType(BaseModel):
    """
    gml:TimeNodePropertyType provides for associating a gml:TimeNode with an object.
    """

    model_config = ConfigDict(defer_build=True)
    time_node: None | TimeNode = field(
        default=None,
        metadata={
            "name": "TimeNode",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class TimeEdgeType(AbstractTimeTopologyPrimitiveType):
    model_config = ConfigDict(defer_build=True)
    start: TimeNodePropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )
    end: TimeNodePropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )
    extent: None | TimePeriodPropertyType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class TimeEdge(TimeEdgeType):
    """
    A time edge is a one-dimensional topological primitive.

    It is an open interval that starts and ends at a node. The edge may be realised as a geometry whose value is a
    time period.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TimeEdgePropertyType(BaseModel):
    """
    gml:TimeEdgePropertyType provides for associating a gml:TimeEdge with an object.
    """

    model_config = ConfigDict(defer_build=True)
    time_edge: None | TimeEdge = field(
        default=None,
        metadata={
            "name": "TimeEdge",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class TimeTopologyPrimitivePropertyType(BaseModel):
    """
    gml:TimeTopologyPrimitivePropertyType provides for associating a gml:AbstractTimeTopologyPrimitive with an
    object.
    """

    model_config = ConfigDict(defer_build=True)
    time_edge: None | TimeEdge = field(
        default=None,
        metadata={
            "name": "TimeEdge",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    time_node: None | TimeNode = field(
        default=None,
        metadata={
            "name": "TimeNode",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class TimeTopologyComplexType(AbstractTimeComplexType):
    model_config = ConfigDict(defer_build=True)
    primitive: list[TimeTopologyPrimitivePropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
            "min_occurs": 1,
        },
    )


class TimeTopologyComplex(TimeTopologyComplexType):
    """
    A temporal topology complex shall be the connected acyclic directed graph composed of temporal topological
    primitives, i.e. time nodes and time edges.

    Because a time edge may not exist without two time nodes on its boundaries, static features have time edges from
    a temporal topology complex as the values of their temporal properties, regardless of explicit declarations. A
    temporal topology complex expresses a linear or a non-linear graph. A temporal linear graph, composed of a
    sequence of time edges, provides a lineage described only by "substitution" of feature instances or feature
    element values. A time node as the start or the end of the graph connects with at least one time edge. A time
    node other than the start and the end shall connect to at least two time edges: one of starting from the node,
    and another ending at the node. A temporal topological complex is a set of connected temporal topological
    primitives. The member primtives are indicated, either by reference or by value, using the primitive property.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TimeTopologyComplexPropertyType(BaseModel):
    """
    gml:TimeTopologyComplexPropertyType provides for associating a gml:TimeTopologyComplex with an object.
    """

    model_config = ConfigDict(defer_build=True)
    time_topology_complex: None | TimeTopologyComplex = field(
        default=None,
        metadata={
            "name": "TimeTopologyComplex",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
