codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "0...100"
  flags:
    backend:
      carryforward: true
      paths:
        - backend/src/
    auth:
      carryforward: true
      paths:
        - auth/src/
    frontend:
      carryforward: true
      paths:
        - frontend/src/
    gifts:
      carryforward: true
  status:
    project:
      default:
        target: 95%
        threshold: 0%
    patch:
      default:
        target: 95%
        threshold: 0%
    backend:
      default:
        flags: [backend]
        target: 95%
        threshold: 0%
    auth:
      default:
        flags: [auth]
        target: 95%
        threshold: 0%
    frontend:
      default:
        flags: [frontend]
        target: 95%
        threshold: 0%
    gifts:
      default:
        flags: [gifts]
        target: 95%
        threshold: 0%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
