codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  flags:
    backend:
      carryforward: true
      paths:
        - backend/src/
    auth:
      carryforward: true
      paths:
        - auth/src/
    frontend:
      carryforward: true
      paths:
        - frontend/src/
    gifts:
      carryforward: true
      paths:
        - GIFTs/gifts/
        - GIFTs/validation/
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_not_found: failure
        if_ci_failed: error
      backend:
        target: 75%
        threshold: 0%
        flags:
          - backend
        if_not_found: failure
        if_ci_failed: error
      auth:
        target: 73%
        threshold: 0%
        flags:
          - auth
        if_not_found: failure
        if_ci_failed: error
      frontend:
        target: 75%
        threshold: 0%
        flags:
          - frontend
        if_not_found: failure
        if_ci_failed: error
      gifts:
        target: 75%
        threshold: 0%
        flags:
          - gifts
        if_not_found: failure
        if_ci_failed: error
    patch:
      default:
        target: 30%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
