repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
        args:
          - "--config=.gitleaks.toml"
          - "--redact"

  - repo: local
    hooks:
      - id: make-ci
        name: make ci
        entry: make ci
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
