apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metar-iwxxm
resources:
  - ../../base
  - redirect-apex.yaml
  - ingress-frontend-apex.yaml
patches:
  - path: patch-ingress-api.yaml
  - path: patch-ingress-frontend.yaml
  - path: patch-configmap-api.yaml
  - path: patch-configmap-frontend.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: production
    includeSelectors: false
