apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metar-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.tac-to-iwxxm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metar-api
                port:
                  name: http
  tls:
    - hosts:
        - api.tac-to-iwxxm.com
      secretName: metar-api-tls
