/**
 * Catalog of operator-visible string exports for EV-048 guard scans (TC-EV048-003).
 *
 * Source comments / test files are out of scope — only these runtime strings.
 * [Corpus: product §F7] [Corpus: tests]
 */

import { EXAMPLES } from '@/fixtures/examples/examplesCatalog';
import { SHELL_NAV_LABELS } from '@/app/components/AppShellNav';
import {
  QUALITY_METRICS_DIFF_EMPTY_LABEL,
  QUALITY_METRICS_DIFF_EXPAND_ALL,
  QUALITY_METRICS_DIFF_COLLAPSE_ALL,
  QUALITY_METRICS_DIFF_HEADING,
  QUALITY_METRICS_EMPTY_DIAGNOSTICS,
  QUALITY_METRICS_LINT_HELP,
  QUALITY_METRICS_RESIDUALS_FOLDED,
  QUALITY_METRICS_RESIDUALS_HELP,
  QUALITY_METRICS_RESIDUALS_NOT_FOLDED,
  QUALITY_METRICS_VALIDATE_HELP,
  QUALITY_METRICS_XML_VIEW_HELP,
  QUALITY_METRICS_XML_VIEW_NORMALIZED,
  QUALITY_METRICS_XML_VIEW_RAW,
} from '@/app/components/QualityMetricsDetail';
import {
  QUALITY_METRICS_DEFERRED_LABEL,
  QUALITY_METRICS_DETAIL_LOAD_FAILED,
  QUALITY_METRICS_DETAIL_LOADING,
  QUALITY_METRICS_EMPTY_LIST,
  QUALITY_METRICS_PAGE_SUBTITLE,
  QUALITY_METRICS_PAGE_TITLE,
} from '@/utils/qualityMetricsCopy';
import {
  IWXXM_PRODUCT_CONVERT_ARIA,
  IWXXM_PRODUCT_CONVERT_LABEL,
  IWXXM_PRODUCT_HELP,
} from '@/utils/iwxxmProductCopy';
import {
  BULLETIN_ID_FIELD_ERROR,
  ISSUING_CENTER_FIELD_ERROR,
} from '@/utils/bulletinFieldsCopy';
import {
  SOFT_PREVIEW_HELP,
  SOFT_PREVIEW_LABEL,
} from '@/app/components/SoftPreviewControl';
import {
  PROPAGATE_RESIDUALS_HELP,
  PROPAGATE_RESIDUALS_LABEL,
} from '@/app/components/PropagateResidualsControl';
import { GUEST_LOSS_OF_PROGRESS_MESSAGE } from '@/utils/guestLossNotice';
import { OPERATOR_HANDBOOK_URL, OPERATOR_ONE_PAGER_URL } from '@/utils/operatorHelp';
import { STORAGE_INVENTORY } from '@/utils/privacyPreferences';
import {
  QUALITY_METRICS_SCHEMA_IMPORT_RESOLVED,
  QUALITY_METRICS_SCHEMA_IMPORT_WARNING,
  QUALITY_METRICS_SCHEMATRON_EVALUATED,
  QUALITY_METRICS_SCHEMATRON_SKIPPED,
} from '@/utils/validateDispositionChips';
import {
  BETA_BADGE_LABEL,
  BETA_FEEDBACK_HELP,
  BETA_FEEDBACK_LINK_LABEL,
} from '@/utils/betaFeedback';
import {
  DISSEMINATION_OPS_AUDIT_EMPTY,
  DISSEMINATION_OPS_AUDIT_HEADING,
  DISSEMINATION_OPS_AUDIT_LOADING,
  DISSEMINATION_OPS_ERROR_PREFIX,
  DISSEMINATION_OPS_HEALTH_EMPTY,
  DISSEMINATION_OPS_HEALTH_HEADING,
  DISSEMINATION_OPS_HEALTH_LOADING,
  DISSEMINATION_OPS_LOGIN_REQUIRED,
  DISSEMINATION_OPS_MAPPING_HEADING,
  DISSEMINATION_OPS_MAPPING_MODE_LABEL,
  DISSEMINATION_OPS_MAPPING_NAME_LABEL,
  DISSEMINATION_OPS_MAPPING_SAVE,
  DISSEMINATION_OPS_PLAN_DEST_LABEL,
  DISSEMINATION_OPS_PLAN_DRY_RUN,
  DISSEMINATION_OPS_PLAN_HEADING,
  DISSEMINATION_OPS_PLAN_POLICY_LABEL,
  DISSEMINATION_OPS_PLAN_SAVE,
  DISSEMINATION_OPS_PLAN_SLUG_LABEL,
  DISSEMINATION_OPS_SIGN_IN,
  DISSEMINATION_OPS_SUBTITLE,
  DISSEMINATION_OPS_TITLE,
} from '@/utils/disseminationOpsCopy';
import {
  CONVERSION_METADATA_CHECKLIST_CONVERT_CONTEXT,
  CONVERSION_METADATA_CHECKLIST_HEADING,
  CONVERSION_METADATA_CHECKLIST_LIBRARIES,
  CONVERSION_METADATA_CHECKLIST_LINT,
  CONVERSION_METADATA_CHECKLIST_MAPPING_BRIDGE,
  CONVERSION_METADATA_CHECKLIST_OPERATOR,
  CONVERSION_METADATA_CHECKLIST_TAC_FINGERPRINT,
  CONVERSION_METADATA_CHECKLIST_YAML_HASHES,
  CONVERSION_METADATA_LINT_BATCH_NOTE,
  CONVERSION_METADATA_PLACEHOLDER_LINT,
  CONVERSION_METADATA_PLACEHOLDER_MAPPING,
  CONVERSION_METADATA_PLACEHOLDER_YAML,
  CONVERSION_METADATA_TOGGLE_HELP,
  CONVERSION_METADATA_TOGGLE_LABEL,
} from '@/utils/conversionExportMetadata';
import {
  CONVERT_OVERLAY_HELP,
  CONVERT_OVERLAY_LABEL,
  CONVERT_OVERLAY_NONE,
  CONVERT_RESET_WMO_LIBRARY_DEFAULTS,
  CONVERT_RESET_WMO_LIBRARY_DEFAULTS_HELP,
  PROFILES_EDITOR_LOGIN_REQUIRED,
  PROFILES_EDITOR_SIGN_IN,
  PROFILES_EDITOR_SUBTITLE,
  PROFILES_EDITOR_TITLE,
  PROFILES_ASSEMBLY_HEADING,
  PROFILES_ASSEMBLY_HELP,
  PROFILES_CONV_TEMPLATES_MODE_CONVERT,
  PROFILES_CONV_TEMPLATES_MODE_DECODE,
  PROFILES_CONV_TEMPLATES_MODE_SKIP,
  PROFILES_CONV_TEMPLATES_ADVANCED,
  PROFILES_ERROR_PREFIX,
  PROFILES_INSPECTOR_EMPTY,
  PROFILES_INSPECTOR_HEADING,
  PROFILES_INSPECTOR_LOADING,
  PROFILES_INSPECTOR_SELECT,
  PROFILES_INSPECTOR_AUTHORITY_ICAO,
  PROFILES_INSPECTOR_COVERAGE_UNAVAILABLE,
  PROFILES_INSPECTOR_FAMILY_ICAO,
  PROFILES_INSPECTOR_FAMILY_NATIONAL,
  PROFILES_LIBRARIES_HEADING,
  PROFILES_LIBRARIES_HELP,
  PROFILES_LIBRARY_LIST_EMPTY,
  PROFILES_LIBRARY_LIST_ERROR,
  PROFILES_LIBRARY_LIST_LOADING,
  PROFILES_LIBRARY_STUB_HELP,
  PROFILES_LIBRARY_TAB_CONVERSION,
  PROFILES_LIBRARY_TAB_DECODING,
  PROFILES_LIBRARY_TAB_DISSEMINATION,
  PROFILES_LIBRARY_TAB_IWXXM_VALIDATION,
  PROFILES_LIBRARY_TAB_OVERVIEW,
  PROFILES_LIBRARY_TAB_TAC_VALIDATION,
  PROFILES_OVERVIEW_COMPARE_STUB,
  PROFILES_OVERVIEW_ENABLEMENT_STUB,
  PROFILES_OVERVIEW_HEADING,
  PROFILES_OVERVIEW_HELP,
  MAPPING_BRIDGE_COL_IWXXM,
  MAPPING_BRIDGE_COL_TAC,
  MAPPING_BRIDGE_COL_TEMPLATE,
  MAPPING_BRIDGE_EMPTY_IWXXM,
  MAPPING_BRIDGE_HEADING,
  MAPPING_BRIDGE_HELP,
  MAPPING_BRIDGE_MATCHED,
  MAPPING_BRIDGE_UNMATCHED,
  MAPPING_BRIDGE_UNMATCHED_HINT,
  PROFILES_OVERLAY_BASE,
  PROFILES_OVERLAY_BODY,
  PROFILES_OVERLAY_HINT,
  PROFILES_OVERLAY_SAVE,
  PROFILES_OVERLAY_SLUG,
  PROFILES_OVERLAYS_EMPTY,
  PROFILES_OVERLAYS_HEADING,
  PROFILES_OVERLAYS_LOADING,
  PROFILES_PACK_EXPORT,
  PROFILES_PACK_MESSAGE,
  PROFILES_PACK_PRODUCT,
  PROFILES_PACK_PROFILE,
  PROFILES_PACK_REF,
  PROFILES_PACK_SAVE,
  PROFILES_PACK_SEVERITY,
  PROFILES_PACK_SLUG,
  PROFILES_PACK_STAGE,
  PROFILES_PACK_WHEN,
  PROFILES_PACKS_EMPTY,
  PROFILES_PACKS_HEADING,
  PROFILES_PACKS_LOADING,
  PROFILES_DRAFT_BLOCKS_HEADING,
  PROFILES_DRAFT_BLOCKS_HELP,
  PROFILES_DRAFT_BLOCK_CLOUD,
  PROFILES_DRAFT_BLOCK_OBSERVATION,
  PROFILES_DRAFT_BLOCK_RVR,
  PROFILES_DRAFT_CARD_CLOUD_AMOUNT,
  PROFILES_DRAFT_CARD_RVR,
  PROFILES_DRAFT_CARD_VISIBILITY,
  PROFILES_DRAFT_CARD_WIND,
  PROFILES_DRAFT_DUPLICATE,
  PROFILES_DRAFT_HEADING,
  PROFILES_DRAFT_HELP,
  PROFILES_DRAFT_IMPORT_LABEL,
  PROFILES_DRAFT_IMPORT_PLACEHOLDER,
  PROFILES_DRAFT_NEW_TEMPLATE,
  PROFILES_DRAFT_SAVE,
  PROFILES_DRAFT_ACTIVATE,
  PROFILES_DRAFT_STATUS_DRAFT,
  PROFILES_DRAFT_STATUS_IDLE,
  PROFILES_DRAFT_STATUS_SAVED,
  PROFILES_DRAFT_STATUS_ACTIVATED,
  PROFILES_DRAFT_TOOLTIP_DUPLICATE,
  PROFILES_DRAFT_TOOLTIP_IMPORT,
  PROFILES_DRAFT_TOOLTIP_NEW,
  PROFILES_DRAFT_TOOLTIP_SAVE,
  PROFILES_DRAFT_TOOLTIP_ACTIVATE,
  PROFILES_DRAFT_DIAGNOSTICS_HEADING,
  PROFILES_DRAFT_DIAGNOSTICS_HELP,
  PROFILES_DRAFT_CAPTURES_HEADING,
  PROFILES_DRAFT_YAML_LOCK,
  PROFILES_DRAFT_ACTIVATE_BLOCKED,
  PROFILES_DRAFT_SAMPLE_HEADING,
  PROFILES_DRAFT_SAMPLE_HELP,
  PROFILES_DRAFT_SAMPLE_PLACEHOLDER,
  PROFILES_INSPECTOR_ACCESS_BUILTIN,
  PROFILES_INSPECTOR_STATUS_DRAFT,
  PROFILES_INSPECTOR_STATUS_READY,
  PROFILES_PROFILE_AUTHORITY,
  PROFILES_PROFILE_COVERAGE,
  PROFILES_PROFILE_FAMILY,
  PROFILES_TOOLTIP_INSPECTOR_COMPARE,
  PROFILES_TOOLTIP_INSPECTOR_PROFILE,
  PROFILES_TOOLTIP_LIBRARIES,
  PROFILES_TOOLTIP_LIBRARY_TAB_CONVERSION,
  PROFILES_TOOLTIP_LIBRARY_TAB_DECODING,
  PROFILES_TOOLTIP_LIBRARY_TAB_DISSEMINATION,
  PROFILES_TOOLTIP_LIBRARY_TAB_IWXXM_VALIDATION,
  PROFILES_TOOLTIP_LIBRARY_TAB_OVERVIEW,
  PROFILES_TOOLTIP_LIBRARY_TAB_TAC_VALIDATION,
  PROFILES_TOOLTIP_PROFILE_BLOCKS,
  PROFILES_TOOLTIP_WORKBENCH,
  PROFILES_WORKBENCH_CATALOG_LABEL,
  PROFILES_WORKBENCH_EDITOR_LABEL,
  PROFILES_WORKBENCH_PREVIEW_IWXXM,
  PROFILES_WORKBENCH_PREVIEW_IWXXM_HELP,
  PROFILES_WORKBENCH_PREVIEW_IWXXM_PLACEHOLDER,
  PROFILES_WORKBENCH_PREVIEW_ISSUES,
  PROFILES_WORKBENCH_PREVIEW_ISSUES_HELP,
  PROFILES_WORKBENCH_PREVIEW_ISSUES_PLACEHOLDER,
} from '@/utils/conversionProfilesCopy';

export type OperatorVisibleCopyEntry = {
  id: string;
  text: string;
};

/**
 * Collect agreed FE string catalogs for the internal-doc-ref guard.
 *
 * @returns Flat list of `{ id, text }` entries
 */
export function collectOperatorVisibleCopy(): OperatorVisibleCopyEntry[] {
  const entries: OperatorVisibleCopyEntry[] = [
    { id: 'soft-preview.label', text: SOFT_PREVIEW_LABEL },
    { id: 'soft-preview.help', text: SOFT_PREVIEW_HELP },
    { id: 'propagate-residuals.label', text: PROPAGATE_RESIDUALS_LABEL },
    { id: 'propagate-residuals.help', text: PROPAGATE_RESIDUALS_HELP },
    { id: 'iwxxm-product.help', text: IWXXM_PRODUCT_HELP },
    { id: 'iwxxm-product.convert-label', text: IWXXM_PRODUCT_CONVERT_LABEL },
    { id: 'iwxxm-product.convert-aria', text: IWXXM_PRODUCT_CONVERT_ARIA },
    { id: 'bulletin-id.field-error', text: BULLETIN_ID_FIELD_ERROR },
    { id: 'issuing-center.field-error', text: ISSUING_CENTER_FIELD_ERROR },
    { id: 'guest.loss-of-progress', text: GUEST_LOSS_OF_PROGRESS_MESSAGE },
    { id: 'help.one-pager-url', text: OPERATOR_ONE_PAGER_URL },
    { id: 'help.handbook-url', text: OPERATOR_HANDBOOK_URL },
    { id: 'shell.nav.convert', text: SHELL_NAV_LABELS.converter },
    { id: 'shell.nav.history', text: SHELL_NAV_LABELS.history },
    { id: 'shell.nav.quality', text: SHELL_NAV_LABELS.quality },
    { id: 'shell.nav.catalog', text: SHELL_NAV_LABELS.catalog },
    {
      id: 'shell.nav.dissemination-ops',
      text: SHELL_NAV_LABELS['dissemination-ops'],
    },
    {
      id: 'shell.nav.profiles',
      text: SHELL_NAV_LABELS.profiles,
    },
    { id: 'profiles.title', text: PROFILES_EDITOR_TITLE },
    { id: 'profiles.subtitle', text: PROFILES_EDITOR_SUBTITLE },
    { id: 'profiles.assembly-heading', text: PROFILES_ASSEMBLY_HEADING },
    { id: 'profiles.assembly-help', text: PROFILES_ASSEMBLY_HELP },
    { id: 'profiles.libraries-heading', text: PROFILES_LIBRARIES_HEADING },
    { id: 'profiles.libraries-help', text: PROFILES_LIBRARIES_HELP },
    {
      id: 'profiles.library-tab-conversion',
      text: PROFILES_LIBRARY_TAB_CONVERSION,
    },
    {
      id: 'profiles.library-tab-tac-validation',
      text: PROFILES_LIBRARY_TAB_TAC_VALIDATION,
    },
    {
      id: 'profiles.library-tab-iwxxm-validation',
      text: PROFILES_LIBRARY_TAB_IWXXM_VALIDATION,
    },
    {
      id: 'profiles.library-tab-dissemination',
      text: PROFILES_LIBRARY_TAB_DISSEMINATION,
    },
    { id: 'profiles.library-tab-decoding', text: PROFILES_LIBRARY_TAB_DECODING },
    { id: 'profiles.library-tab-overview', text: PROFILES_LIBRARY_TAB_OVERVIEW },
    { id: 'profiles.overview-heading', text: PROFILES_OVERVIEW_HEADING },
    { id: 'profiles.overview-help', text: PROFILES_OVERVIEW_HELP },
    { id: 'profiles.overview-compare-stub', text: PROFILES_OVERVIEW_COMPARE_STUB },
    {
      id: 'profiles.overview-enablement-stub',
      text: PROFILES_OVERVIEW_ENABLEMENT_STUB,
    },
    { id: 'profiles.workbench-catalog', text: PROFILES_WORKBENCH_CATALOG_LABEL },
    { id: 'profiles.workbench-editor', text: PROFILES_WORKBENCH_EDITOR_LABEL },
    { id: 'profiles.workbench-preview-iwxxm', text: PROFILES_WORKBENCH_PREVIEW_IWXXM },
    {
      id: 'profiles.workbench-preview-iwxxm-help',
      text: PROFILES_WORKBENCH_PREVIEW_IWXXM_HELP,
    },
    {
      id: 'profiles.workbench-preview-iwxxm-placeholder',
      text: PROFILES_WORKBENCH_PREVIEW_IWXXM_PLACEHOLDER,
    },
    {
      id: 'profiles.workbench-preview-issues',
      text: PROFILES_WORKBENCH_PREVIEW_ISSUES,
    },
    {
      id: 'profiles.workbench-preview-issues-help',
      text: PROFILES_WORKBENCH_PREVIEW_ISSUES_HELP,
    },
    {
      id: 'profiles.workbench-preview-issues-placeholder',
      text: PROFILES_WORKBENCH_PREVIEW_ISSUES_PLACEHOLDER,
    },
    { id: 'profiles.tooltip-workbench', text: PROFILES_TOOLTIP_WORKBENCH },
    { id: 'profiles.library-list-loading', text: PROFILES_LIBRARY_LIST_LOADING },
    { id: 'profiles.library-list-empty', text: PROFILES_LIBRARY_LIST_EMPTY },
    { id: 'profiles.library-list-error', text: PROFILES_LIBRARY_LIST_ERROR },
    { id: 'profiles.library-stub-help', text: PROFILES_LIBRARY_STUB_HELP },
    { id: 'mapping-bridge.heading', text: MAPPING_BRIDGE_HEADING },
    { id: 'mapping-bridge.help', text: MAPPING_BRIDGE_HELP },
    { id: 'mapping-bridge.col-tac', text: MAPPING_BRIDGE_COL_TAC },
    { id: 'mapping-bridge.col-template', text: MAPPING_BRIDGE_COL_TEMPLATE },
    { id: 'mapping-bridge.col-iwxxm', text: MAPPING_BRIDGE_COL_IWXXM },
    { id: 'mapping-bridge.matched', text: MAPPING_BRIDGE_MATCHED },
    { id: 'mapping-bridge.unmatched', text: MAPPING_BRIDGE_UNMATCHED },
    { id: 'mapping-bridge.unmatched-hint', text: MAPPING_BRIDGE_UNMATCHED_HINT },
    { id: 'mapping-bridge.empty-iwxxm', text: MAPPING_BRIDGE_EMPTY_IWXXM },
    {
      id: 'profiles.token-mode-convert',
      text: PROFILES_CONV_TEMPLATES_MODE_CONVERT,
    },
    {
      id: 'profiles.token-mode-decode',
      text: PROFILES_CONV_TEMPLATES_MODE_DECODE,
    },
    { id: 'profiles.token-mode-skip', text: PROFILES_CONV_TEMPLATES_MODE_SKIP },
    { id: 'profiles.token-advanced', text: PROFILES_CONV_TEMPLATES_ADVANCED },
    { id: 'profiles.login-required', text: PROFILES_EDITOR_LOGIN_REQUIRED },
    { id: 'profiles.sign-in', text: PROFILES_EDITOR_SIGN_IN },
    { id: 'profiles.inspector-heading', text: PROFILES_INSPECTOR_HEADING },
    { id: 'profiles.inspector-loading', text: PROFILES_INSPECTOR_LOADING },
    { id: 'profiles.inspector-empty', text: PROFILES_INSPECTOR_EMPTY },
    { id: 'profiles.inspector-select', text: PROFILES_INSPECTOR_SELECT },
    {
      id: 'profiles.inspector-family-icao',
      text: PROFILES_INSPECTOR_FAMILY_ICAO,
    },
    {
      id: 'profiles.inspector-family-national',
      text: PROFILES_INSPECTOR_FAMILY_NATIONAL,
    },
    {
      id: 'profiles.inspector-authority-icao',
      text: PROFILES_INSPECTOR_AUTHORITY_ICAO,
    },
    {
      id: 'profiles.inspector-coverage-unavailable',
      text: PROFILES_INSPECTOR_COVERAGE_UNAVAILABLE,
    },
    { id: 'profiles.packs-heading', text: PROFILES_PACKS_HEADING },
    { id: 'profiles.packs-loading', text: PROFILES_PACKS_LOADING },
    { id: 'profiles.packs-empty', text: PROFILES_PACKS_EMPTY },
    { id: 'profiles.pack-slug', text: PROFILES_PACK_SLUG },
    { id: 'profiles.pack-profile', text: PROFILES_PACK_PROFILE },
    { id: 'profiles.pack-product', text: PROFILES_PACK_PRODUCT },
    { id: 'profiles.pack-stage', text: PROFILES_PACK_STAGE },
    { id: 'profiles.pack-severity', text: PROFILES_PACK_SEVERITY },
    { id: 'profiles.pack-when', text: PROFILES_PACK_WHEN },
    { id: 'profiles.pack-message', text: PROFILES_PACK_MESSAGE },
    { id: 'profiles.pack-ref', text: PROFILES_PACK_REF },
    { id: 'profiles.pack-save', text: PROFILES_PACK_SAVE },
    { id: 'profiles.pack-export', text: PROFILES_PACK_EXPORT },
    { id: 'profiles.overlays-heading', text: PROFILES_OVERLAYS_HEADING },
    { id: 'profiles.overlays-loading', text: PROFILES_OVERLAYS_LOADING },
    { id: 'profiles.overlays-empty', text: PROFILES_OVERLAYS_EMPTY },
    { id: 'profiles.overlay-slug', text: PROFILES_OVERLAY_SLUG },
    { id: 'profiles.overlay-base', text: PROFILES_OVERLAY_BASE },
    { id: 'profiles.overlay-body', text: PROFILES_OVERLAY_BODY },
    { id: 'profiles.overlay-save', text: PROFILES_OVERLAY_SAVE },
    { id: 'profiles.overlay-hint', text: PROFILES_OVERLAY_HINT },
    { id: 'profiles.convert-overlay-label', text: CONVERT_OVERLAY_LABEL },
    { id: 'profiles.convert-overlay-none', text: CONVERT_OVERLAY_NONE },
    { id: 'profiles.convert-overlay-help', text: CONVERT_OVERLAY_HELP },
    { id: 'profiles.error-prefix', text: PROFILES_ERROR_PREFIX },
    {
      id: 'convert.reset-wmo-library-defaults',
      text: CONVERT_RESET_WMO_LIBRARY_DEFAULTS,
    },
    {
      id: 'convert.reset-wmo-library-defaults-help',
      text: CONVERT_RESET_WMO_LIBRARY_DEFAULTS_HELP,
    },
    {
      id: 'conversion-metadata.toggle-label',
      text: CONVERSION_METADATA_TOGGLE_LABEL,
    },
    {
      id: 'conversion-metadata.toggle-help',
      text: CONVERSION_METADATA_TOGGLE_HELP,
    },
    {
      id: 'conversion-metadata.checklist-heading',
      text: CONVERSION_METADATA_CHECKLIST_HEADING,
    },
    {
      id: 'conversion-metadata.checklist-libraries',
      text: CONVERSION_METADATA_CHECKLIST_LIBRARIES,
    },
    {
      id: 'conversion-metadata.checklist-yaml-hashes',
      text: CONVERSION_METADATA_CHECKLIST_YAML_HASHES,
    },
    {
      id: 'conversion-metadata.checklist-convert-context',
      text: CONVERSION_METADATA_CHECKLIST_CONVERT_CONTEXT,
    },
    {
      id: 'conversion-metadata.checklist-operator',
      text: CONVERSION_METADATA_CHECKLIST_OPERATOR,
    },
    {
      id: 'conversion-metadata.checklist-lint',
      text: CONVERSION_METADATA_CHECKLIST_LINT,
    },
    {
      id: 'conversion-metadata.checklist-tac-fingerprint',
      text: CONVERSION_METADATA_CHECKLIST_TAC_FINGERPRINT,
    },
    {
      id: 'conversion-metadata.checklist-mapping-bridge',
      text: CONVERSION_METADATA_CHECKLIST_MAPPING_BRIDGE,
    },
    {
      id: 'conversion-metadata.placeholder-yaml',
      text: CONVERSION_METADATA_PLACEHOLDER_YAML,
    },
    {
      id: 'conversion-metadata.placeholder-lint',
      text: CONVERSION_METADATA_PLACEHOLDER_LINT,
    },
    {
      id: 'conversion-metadata.lint-batch-note',
      text: CONVERSION_METADATA_LINT_BATCH_NOTE,
    },
    {
      id: 'conversion-metadata.placeholder-mapping',
      text: CONVERSION_METADATA_PLACEHOLDER_MAPPING,
    },
    { id: 'profiles.tooltip-libraries', text: PROFILES_TOOLTIP_LIBRARIES },
    {
      id: 'profiles.tooltip-library-tab-conversion',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_CONVERSION,
    },
    {
      id: 'profiles.tooltip-library-tab-tac-validation',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_TAC_VALIDATION,
    },
    {
      id: 'profiles.tooltip-library-tab-iwxxm-validation',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_IWXXM_VALIDATION,
    },
    {
      id: 'profiles.tooltip-library-tab-dissemination',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_DISSEMINATION,
    },
    {
      id: 'profiles.tooltip-library-tab-decoding',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_DECODING,
    },
    {
      id: 'profiles.tooltip-library-tab-overview',
      text: PROFILES_TOOLTIP_LIBRARY_TAB_OVERVIEW,
    },
    {
      id: 'profiles.tooltip-inspector-profile',
      text: PROFILES_TOOLTIP_INSPECTOR_PROFILE,
    },
    {
      id: 'profiles.tooltip-inspector-compare',
      text: PROFILES_TOOLTIP_INSPECTOR_COMPARE,
    },
    {
      id: 'profiles.tooltip-profile-blocks',
      text: PROFILES_TOOLTIP_PROFILE_BLOCKS,
    },
    { id: 'profiles.profile-family', text: PROFILES_PROFILE_FAMILY },
    { id: 'profiles.profile-authority', text: PROFILES_PROFILE_AUTHORITY },
    { id: 'profiles.profile-coverage', text: PROFILES_PROFILE_COVERAGE },
    {
      id: 'profiles.inspector-access-builtin',
      text: PROFILES_INSPECTOR_ACCESS_BUILTIN,
    },
    {
      id: 'profiles.inspector-status-ready',
      text: PROFILES_INSPECTOR_STATUS_READY,
    },
    {
      id: 'profiles.inspector-status-draft',
      text: PROFILES_INSPECTOR_STATUS_DRAFT,
    },
    { id: 'profiles.draft-heading', text: PROFILES_DRAFT_HEADING },
    { id: 'profiles.draft-help', text: PROFILES_DRAFT_HELP },
    { id: 'profiles.draft-new-template', text: PROFILES_DRAFT_NEW_TEMPLATE },
    { id: 'profiles.draft-duplicate', text: PROFILES_DRAFT_DUPLICATE },
    { id: 'profiles.draft-import-label', text: PROFILES_DRAFT_IMPORT_LABEL },
    {
      id: 'profiles.draft-import-placeholder',
      text: PROFILES_DRAFT_IMPORT_PLACEHOLDER,
    },
    { id: 'profiles.draft-save', text: PROFILES_DRAFT_SAVE },
    { id: 'profiles.draft-activate', text: PROFILES_DRAFT_ACTIVATE },
    { id: 'profiles.draft-status-idle', text: PROFILES_DRAFT_STATUS_IDLE },
    { id: 'profiles.draft-status-draft', text: PROFILES_DRAFT_STATUS_DRAFT },
    { id: 'profiles.draft-status-saved', text: PROFILES_DRAFT_STATUS_SAVED },
    { id: 'profiles.draft-status-activated', text: PROFILES_DRAFT_STATUS_ACTIVATED },
    {
      id: 'profiles.draft-blocks-heading',
      text: PROFILES_DRAFT_BLOCKS_HEADING,
    },
    { id: 'profiles.draft-blocks-help', text: PROFILES_DRAFT_BLOCKS_HELP },
    {
      id: 'profiles.draft-block-observation',
      text: PROFILES_DRAFT_BLOCK_OBSERVATION,
    },
    { id: 'profiles.draft-block-cloud', text: PROFILES_DRAFT_BLOCK_CLOUD },
    { id: 'profiles.draft-block-rvr', text: PROFILES_DRAFT_BLOCK_RVR },
    { id: 'profiles.draft-card-wind', text: PROFILES_DRAFT_CARD_WIND },
    {
      id: 'profiles.draft-card-visibility',
      text: PROFILES_DRAFT_CARD_VISIBILITY,
    },
    {
      id: 'profiles.draft-card-cloud-amount',
      text: PROFILES_DRAFT_CARD_CLOUD_AMOUNT,
    },
    { id: 'profiles.draft-card-rvr', text: PROFILES_DRAFT_CARD_RVR },
    { id: 'profiles.draft-tooltip-new', text: PROFILES_DRAFT_TOOLTIP_NEW },
    {
      id: 'profiles.draft-tooltip-duplicate',
      text: PROFILES_DRAFT_TOOLTIP_DUPLICATE,
    },
    { id: 'profiles.draft-tooltip-import', text: PROFILES_DRAFT_TOOLTIP_IMPORT },
    { id: 'profiles.draft-tooltip-save', text: PROFILES_DRAFT_TOOLTIP_SAVE },
    { id: 'profiles.draft-tooltip-activate', text: PROFILES_DRAFT_TOOLTIP_ACTIVATE },
    {
      id: 'profiles.draft-diagnostics-heading',
      text: PROFILES_DRAFT_DIAGNOSTICS_HEADING,
    },
    { id: 'profiles.draft-diagnostics-help', text: PROFILES_DRAFT_DIAGNOSTICS_HELP },
    { id: 'profiles.draft-captures-heading', text: PROFILES_DRAFT_CAPTURES_HEADING },
    { id: 'profiles.draft-yaml-lock', text: PROFILES_DRAFT_YAML_LOCK },
    { id: 'profiles.draft-activate-blocked', text: PROFILES_DRAFT_ACTIVATE_BLOCKED },
    { id: 'profiles.draft-sample-heading', text: PROFILES_DRAFT_SAMPLE_HEADING },
    { id: 'profiles.draft-sample-help', text: PROFILES_DRAFT_SAMPLE_HELP },
    {
      id: 'profiles.draft-sample-placeholder',
      text: PROFILES_DRAFT_SAMPLE_PLACEHOLDER,
    },
    { id: 'dissemination-ops.title', text: DISSEMINATION_OPS_TITLE },
    { id: 'dissemination-ops.subtitle', text: DISSEMINATION_OPS_SUBTITLE },
    { id: 'beta.badge', text: BETA_BADGE_LABEL },
    { id: 'beta.feedback-help', text: BETA_FEEDBACK_HELP },
    { id: 'beta.feedback-link', text: BETA_FEEDBACK_LINK_LABEL },
    {
      id: 'dissemination-ops.login-required',
      text: DISSEMINATION_OPS_LOGIN_REQUIRED,
    },
    { id: 'dissemination-ops.sign-in', text: DISSEMINATION_OPS_SIGN_IN },
    {
      id: 'dissemination-ops.health-heading',
      text: DISSEMINATION_OPS_HEALTH_HEADING,
    },
    {
      id: 'dissemination-ops.health-loading',
      text: DISSEMINATION_OPS_HEALTH_LOADING,
    },
    {
      id: 'dissemination-ops.health-empty',
      text: DISSEMINATION_OPS_HEALTH_EMPTY,
    },
    {
      id: 'dissemination-ops.audit-heading',
      text: DISSEMINATION_OPS_AUDIT_HEADING,
    },
    {
      id: 'dissemination-ops.audit-loading',
      text: DISSEMINATION_OPS_AUDIT_LOADING,
    },
    { id: 'dissemination-ops.audit-empty', text: DISSEMINATION_OPS_AUDIT_EMPTY },
    { id: 'dissemination-ops.plan-heading', text: DISSEMINATION_OPS_PLAN_HEADING },
    {
      id: 'dissemination-ops.plan-slug',
      text: DISSEMINATION_OPS_PLAN_SLUG_LABEL,
    },
    {
      id: 'dissemination-ops.plan-policy',
      text: DISSEMINATION_OPS_PLAN_POLICY_LABEL,
    },
    {
      id: 'dissemination-ops.plan-dest',
      text: DISSEMINATION_OPS_PLAN_DEST_LABEL,
    },
    { id: 'dissemination-ops.plan-save', text: DISSEMINATION_OPS_PLAN_SAVE },
    {
      id: 'dissemination-ops.plan-dry-run',
      text: DISSEMINATION_OPS_PLAN_DRY_RUN,
    },
    {
      id: 'dissemination-ops.mapping-heading',
      text: DISSEMINATION_OPS_MAPPING_HEADING,
    },
    {
      id: 'dissemination-ops.mapping-name',
      text: DISSEMINATION_OPS_MAPPING_NAME_LABEL,
    },
    {
      id: 'dissemination-ops.mapping-mode',
      text: DISSEMINATION_OPS_MAPPING_MODE_LABEL,
    },
    {
      id: 'dissemination-ops.mapping-save',
      text: DISSEMINATION_OPS_MAPPING_SAVE,
    },
    {
      id: 'dissemination-ops.error-prefix',
      text: DISSEMINATION_OPS_ERROR_PREFIX,
    },
    { id: 'quality-metrics.title', text: QUALITY_METRICS_PAGE_TITLE },
    { id: 'quality-metrics.subtitle', text: QUALITY_METRICS_PAGE_SUBTITLE },
    { id: 'quality-metrics.deferred-label', text: QUALITY_METRICS_DEFERRED_LABEL },
    { id: 'quality-metrics.empty-list', text: QUALITY_METRICS_EMPTY_LIST },
    {
      id: 'quality-metrics.detail-load-failed',
      text: QUALITY_METRICS_DETAIL_LOAD_FAILED,
    },
    {
      id: 'quality-metrics.detail-loading',
      text: QUALITY_METRICS_DETAIL_LOADING,
    },
    { id: 'quality-metrics.diff-empty', text: QUALITY_METRICS_DIFF_EMPTY_LABEL },
    { id: 'quality-metrics.diff-heading', text: QUALITY_METRICS_DIFF_HEADING },
    {
      id: 'quality-metrics.diff-expand-all',
      text: QUALITY_METRICS_DIFF_EXPAND_ALL,
    },
    {
      id: 'quality-metrics.diff-collapse-all',
      text: QUALITY_METRICS_DIFF_COLLAPSE_ALL,
    },
    {
      id: 'quality-metrics.empty-diagnostics',
      text: QUALITY_METRICS_EMPTY_DIAGNOSTICS,
    },
    { id: 'quality-metrics.residuals-help', text: QUALITY_METRICS_RESIDUALS_HELP },
    {
      id: 'quality-metrics.residuals-folded',
      text: QUALITY_METRICS_RESIDUALS_FOLDED,
    },
    {
      id: 'quality-metrics.residuals-not-folded',
      text: QUALITY_METRICS_RESIDUALS_NOT_FOLDED,
    },
    { id: 'quality-metrics.lint-help', text: QUALITY_METRICS_LINT_HELP },
    { id: 'quality-metrics.validate-help', text: QUALITY_METRICS_VALIDATE_HELP },
    {
      id: 'quality-metrics.xml-view-normalized',
      text: QUALITY_METRICS_XML_VIEW_NORMALIZED,
    },
    { id: 'quality-metrics.xml-view-raw', text: QUALITY_METRICS_XML_VIEW_RAW },
    { id: 'quality-metrics.xml-view-help', text: QUALITY_METRICS_XML_VIEW_HELP },
    {
      id: 'quality-metrics.schematron-evaluated',
      text: QUALITY_METRICS_SCHEMATRON_EVALUATED,
    },
    {
      id: 'quality-metrics.schematron-skipped',
      text: QUALITY_METRICS_SCHEMATRON_SKIPPED,
    },
    {
      id: 'quality-metrics.schema-import-resolved',
      text: QUALITY_METRICS_SCHEMA_IMPORT_RESOLVED,
    },
    {
      id: 'quality-metrics.schema-import-warning',
      text: QUALITY_METRICS_SCHEMA_IMPORT_WARNING,
    },
  ];

  for (const item of STORAGE_INVENTORY) {
    entries.push({
      id: `privacy.inventory.${item.kind}`,
      text: item.purpose,
    });
  }

  for (const example of EXAMPLES) {
    entries.push({
      id: `examples.${example.id}.label`,
      text: example.label,
    });
  }

  return entries;
}
