"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:16

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import ConfigDict
from xsdata_pydantic.fields import field

from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    MeasureType,
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.measures import (
    AngleType,
    LengthType,
    SpeedType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2023-1"


class AngleWithNilReasonType(AngleType):
    model_config = ConfigDict(defer_build=True)
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class DistanceWithNilReasonType(LengthType):
    model_config = ConfigDict(defer_build=True)
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class LengthWithNilReasonType(LengthType):
    model_config = ConfigDict(defer_build=True)
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class MeasureWithNilReasonType(MeasureType):
    model_config = ConfigDict(defer_build=True)
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class VelocityWithNilReasonType(SpeedType):
    model_config = ConfigDict(defer_build=True)
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class AngleWithNilReason(AngleWithNilReasonType):
    """
    A nillable Angle quantity.

    Unlike the base Angle measure, references to this type may be nil and may include a nilReason.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class DistanceWithNilReason(DistanceWithNilReasonType):
    """
    A nillable Distance quantity.

    Unlike the base Distance measure, references to this type may be nil and may include a nilReason.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class LengthWithNilReason(LengthWithNilReasonType):
    """
    A nillable Length quantity.

    Unlike the base Length measure, references to this type may be nil and include a nilReason.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class MeasureWithNilReason(MeasureWithNilReasonType):
    """
    A nillable Measure quantity.

    Unlike the base measure, references to this type may be nil and may include a nilReason.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class VelocityWithNilReason(VelocityWithNilReasonType):
    """
    A nillable Velocity quantity.

    Unlike the base Velocity measure, references to this type may be nil and may include a nilReason.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)
