"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:16

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from .common import (
    AbstractTimeObjectPropertyType,
    AirspaceVolumePropertyType,
    ExtensionType,
    ReportType,
    StringWithNilReasonType,
    TimeIndicatorType,
    UnitPropertyType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.feature import AbstractFeatureType
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.gml_base import ReferenceType
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.temporal import TimeInstantPropertyType
from .xlink import (
    ActuateType,
    ShowType,
    TypeType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2023-1"


class SpaceWeatherLocationType(ReferenceType):
    pass
    model_config = ConfigDict(defer_build=True)


class SpaceWeatherPhenomenaType(ReferenceType):
    pass
    model_config = ConfigDict(defer_build=True)


class SpaceWeatherLocation(SpaceWeatherLocationType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherPhenomena(SpaceWeatherPhenomenaType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherRegionType(AbstractFeatureType):
    """
    Parameters
    ----------
    location
        The geographic location at which space weather phenomena occur
    location_indicator
        The geographic area code, such as high northern latitudes
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherRegion
    """

    model_config = ConfigDict(defer_build=True)
    location: AirspaceVolumePropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        }
    )
    location_indicator: SpaceWeatherLocationType = field(
        metadata={
            "name": "locationIndicator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        }
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )


class SpaceWeatherRegion(SpaceWeatherRegionType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherRegionPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_region: None | SpaceWeatherRegion = field(
        default=None,
        metadata={
            "name": "SpaceWeatherRegion",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpaceWeatherAnalysisType(AbstractFeatureType):
    """
    Parameters
    ----------
    phenomenon_time
        The time at which meteorological phenomena occur
    region
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherAnalysis
    time_indicator
        Indicator of observed or forecast conditions
    """

    model_config = ConfigDict(defer_build=True)
    phenomenon_time: AbstractTimeObjectPropertyType = field(
        metadata={
            "name": "phenomenonTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        }
    )
    region: list[SpaceWeatherRegionPropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
            "min_occurs": 1,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    time_indicator: TimeIndicatorType = field(
        metadata={
            "name": "timeIndicator",
            "type": "Attribute",
        }
    )


class SpaceWeatherAnalysis(SpaceWeatherAnalysisType):
    """
    Observed or forecast space weather phenomena.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherAnalysisPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_analysis: None | SpaceWeatherAnalysis = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAnalysis",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpaceWeatherAdvisoryType(ReportType):
    """
    Parameters
    ----------
    issue_time
        The time at which this report was issued
    issuing_space_weather_centre
        The issuing space weather centre (SWXC)
    advisory_number
        Advisory number: four digit year and unique message number.  Example "2018/1"
    replaced_advisory_number
        The number of the advisory being replaced.  Example "2018/1"
    phenomenon
        The space weather phenomenon, such as radiation or satellite communication
    analysis
        Observed and forecast space weather information.  Analyses should be reported in the order in which they
        occur, starting with the initial observed/forecast conditions and proceeding through each subsequent forecast
        to the end of the period
    remarks
        Remarks, as necessary. When the remark is nil, it should be indicated by a missing remarks with a nil reason
        of 'inapplicable'
    next_advisory_time
        The time at which the next advisory will be issued Use attribute indeterminatePosition to element
        timePosition to indicate if the actual temporal position is before or after the specified value. When no
        subsequent advisory is expected to be issued it should be indicated by a missing expected advisory time with
        a nil reason of 'inapplicable'
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherAdvisory
    """

    model_config = ConfigDict(defer_build=True)
    issue_time: TimeInstantPropertyType = field(
        metadata={
            "name": "issueTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        }
    )
    issuing_space_weather_centre: UnitPropertyType = field(
        metadata={
            "name": "issuingSpaceWeatherCentre",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        }
    )
    advisory_number: None | StringWithNilReasonType = field(
        default=None,
        metadata={
            "name": "advisoryNumber",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
            "nillable": True,
        },
    )
    replaced_advisory_number: None | str = field(
        default=None,
        metadata={
            "name": "replacedAdvisoryNumber",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    phenomenon: list[SpaceWeatherPhenomenaType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    analysis: list[SpaceWeatherAnalysisPropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
            "max_occurs": 5,
        },
    )
    remarks: None | StringWithNilReasonType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
            "nillable": True,
        },
    )
    next_advisory_time: None | TimeInstantPropertyType = field(
        default=None,
        metadata={
            "name": "nextAdvisoryTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )


class SpaceWeatherAdvisory(SpaceWeatherAdvisoryType):
    """
    An advisory of space weather conditions of significance to aviation as represented in ICAO Annex 3 / WMO No.
    49-2.

    Volcanic ash advisories are issued by space weather centres (SWXCs).
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2023-1"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherAdvisoryPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_advisory: None | SpaceWeatherAdvisory = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAdvisory",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
