"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:16

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from ........met_feature import (
    ElevatedCurve as MetFeatureElevatedCurve,
)
from ........met_feature import (
    ElevatedLevel,
    ElevatedVolume,
)
from ........met_feature import (
    ElevatedPoint as MetFeatureElevatedPoint,
)
from ........met_feature import (
    ElevatedSurface as MetFeatureElevatedSurface,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    Curve as WwwAixmAeroSchema5AixmFeaturesCurve,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    ElevatedCurve as WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedCurve,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    ElevatedPoint as WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedPoint,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    ElevatedSurface as WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedSurface,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    Point as WwwAixmAeroSchema5AixmFeaturesPoint,
)
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    Surface as WwwAixmAeroSchema5AixmFeaturesSurface,
)
from ........xlink import (
    ActuateType,
    ShowType,
    TypeType,
)
from .....gml.pkg_3.pkg_2.pkg_1.basic_types import NilReasonEnumerationValue
from .....gml.pkg_3.pkg_2.pkg_1.geometry_aggregates import (
    MultiCurve,
    MultiGeometry,
    MultiPoint,
    MultiSolid,
    MultiSurface,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_basic0d1d import (
    LineString,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_basic0d1d import (
    Point as SchemasOpengisNetGml32GeometryBasic0D1DPoint,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_basic2d import (
    LinearRing,
    Polygon,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_complexes import (
    CompositeCurve,
    CompositeSolid,
    CompositeSurface,
    GeometricComplex,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_primitives import (
    Curve as SchemasOpengisNetGml32GeometryPrimitivesCurve,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_primitives import (
    OrientableCurve,
    OrientableSurface,
    PolyhedralSurface,
    Ring,
    Shell,
    Solid,
    Tin,
    TriangulatedSurface,
)
from .....gml.pkg_3.pkg_2.pkg_1.geometry_primitives import (
    Surface as SchemasOpengisNetGml32GeometryPrimitivesSurface,
)
from .....gml.pkg_3.pkg_2.pkg_1.grids import (
    Grid,
    RectifiedGrid,
)

__NAMESPACE__ = "http://www.isotc211.org/2005/gss"


class GmObjectPropertyType(BaseModel):
    class Meta:
        name = "GM_Object_PropertyType"

    model_config = ConfigDict(defer_build=True)
    rectified_grid: None | RectifiedGrid = field(
        default=None,
        metadata={
            "name": "RectifiedGrid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    grid: None | Grid = field(
        default=None,
        metadata={
            "name": "Grid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    geometric_complex: None | GeometricComplex = field(
        default=None,
        metadata={
            "name": "GeometricComplex",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_solid: None | MultiSolid = field(
        default=None,
        metadata={
            "name": "MultiSolid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_surface: None | MultiSurface = field(
        default=None,
        metadata={
            "name": "MultiSurface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_curve: None | MultiCurve = field(
        default=None,
        metadata={
            "name": "MultiCurve",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_point: None | MultiPoint = field(
        default=None,
        metadata={
            "name": "MultiPoint",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_geometry: None | MultiGeometry = field(
        default=None,
        metadata={
            "name": "MultiGeometry",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    elevated_level: None | ElevatedLevel = field(
        default=None,
        metadata={
            "name": "ElevatedLevel",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    composite_solid: None | CompositeSolid = field(
        default=None,
        metadata={
            "name": "CompositeSolid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    solid: None | Solid = field(
        default=None,
        metadata={
            "name": "Solid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    composite_surface: None | CompositeSurface = field(
        default=None,
        metadata={
            "name": "CompositeSurface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    shell: None | Shell = field(
        default=None,
        metadata={
            "name": "Shell",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    orientable_surface: None | OrientableSurface = field(
        default=None,
        metadata={
            "name": "OrientableSurface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    elevated_volume: None | ElevatedVolume = field(
        default=None,
        metadata={
            "name": "ElevatedVolume",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    elevated_surface: None | MetFeatureElevatedSurface = field(
        default=None,
        metadata={
            "name": "ElevatedSurface",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    aixm_aero_schema_5_1_1_elevated_surface: (
        None | WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedSurface
    ) = field(
        default=None,
        metadata={
            "name": "ElevatedSurface",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    surface: None | WwwAixmAeroSchema5AixmFeaturesSurface = field(
        default=None,
        metadata={
            "name": "Surface",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    tin: None | Tin = field(
        default=None,
        metadata={
            "name": "Tin",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    triangulated_surface: None | TriangulatedSurface = field(
        default=None,
        metadata={
            "name": "TriangulatedSurface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    polyhedral_surface: None | PolyhedralSurface = field(
        default=None,
        metadata={
            "name": "PolyhedralSurface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    opengis_net_gml_3_2_surface: (
        None | SchemasOpengisNetGml32GeometryPrimitivesSurface
    ) = field(
        default=None,
        metadata={
            "name": "Surface",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    polygon: None | Polygon = field(
        default=None,
        metadata={
            "name": "Polygon",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    composite_curve: None | CompositeCurve = field(
        default=None,
        metadata={
            "name": "CompositeCurve",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    orientable_curve: None | OrientableCurve = field(
        default=None,
        metadata={
            "name": "OrientableCurve",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    elevated_curve: None | MetFeatureElevatedCurve = field(
        default=None,
        metadata={
            "name": "ElevatedCurve",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    aixm_aero_schema_5_1_1_elevated_curve: (
        None | WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedCurve
    ) = field(
        default=None,
        metadata={
            "name": "ElevatedCurve",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    curve: None | WwwAixmAeroSchema5AixmFeaturesCurve = field(
        default=None,
        metadata={
            "name": "Curve",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    opengis_net_gml_3_2_curve: None | SchemasOpengisNetGml32GeometryPrimitivesCurve = (
        field(
            default=None,
            metadata={
                "name": "Curve",
                "type": "Element",
                "namespace": "http://www.opengis.net/gml/3.2",
            },
        )
    )
    ring: None | Ring = field(
        default=None,
        metadata={
            "name": "Ring",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    linear_ring: None | LinearRing = field(
        default=None,
        metadata={
            "name": "LinearRing",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    line_string: None | LineString = field(
        default=None,
        metadata={
            "name": "LineString",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    elevated_point: None | MetFeatureElevatedPoint = field(
        default=None,
        metadata={
            "name": "ElevatedPoint",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    aixm_aero_schema_5_1_1_elevated_point: (
        None | WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedPoint
    ) = field(
        default=None,
        metadata={
            "name": "ElevatedPoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    point: None | WwwAixmAeroSchema5AixmFeaturesPoint = field(
        default=None,
        metadata={
            "name": "Point",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    opengis_net_gml_3_2_point: None | SchemasOpengisNetGml32GeometryBasic0D1DPoint = (
        field(
            default=None,
            metadata={
                "name": "Point",
                "type": "Element",
                "namespace": "http://www.opengis.net/gml/3.2",
            },
        )
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    uuidref: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "namespace": "http://www.isotc211.org/2005/gco",
            "pattern": r"other:\w{2,}",
        },
    )


class GmPointPropertyType(BaseModel):
    class Meta:
        name = "GM_Point_PropertyType"

    model_config = ConfigDict(defer_build=True)
    elevated_point: None | MetFeatureElevatedPoint = field(
        default=None,
        metadata={
            "name": "ElevatedPoint",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2023-1",
        },
    )
    aixm_aero_schema_5_1_1_elevated_point: (
        None | WwwAixmAeroSchemaPkg5PkgPkgAixmFeaturesElevatedPoint
    ) = field(
        default=None,
        metadata={
            "name": "ElevatedPoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    point: None | WwwAixmAeroSchema5AixmFeaturesPoint = field(
        default=None,
        metadata={
            "name": "Point",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    opengis_net_gml_3_2_point: None | SchemasOpengisNetGml32GeometryBasic0D1DPoint = (
        field(
            default=None,
            metadata={
                "name": "Point",
                "type": "Element",
                "namespace": "http://www.opengis.net/gml/3.2",
            },
        )
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    uuidref: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "namespace": "http://www.isotc211.org/2005/gco",
            "pattern": r"other:\w{2,}",
        },
    )
