"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from .common import (
    AbstractTimeObjectPropertyType,
    AerodromeCloudForecastPropertyType,
    AerodromeForecastWeatherType,
    AerodromeSurfaceWindTrendForecastPropertyType,
    AirportHeliportPropertyType,
    AngleWithNilReasonType,
    CloudLayerPropertyType,
    DistanceWithNilReasonType,
    ExtensionType,
    LengthWithNilReasonType,
    MeasureWithNilReasonType,
    RelationalOperatorType,
    ReportType,
    RunwayDirectionPropertyType,
    VelocityWithNilReasonType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.gml_base import (
    AbstractGmltype,
    ReferenceType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.measures import LengthType
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.temporal import TimeInstantPropertyType
from .xlink import (
    ActuateType,
    ShowType,
    TypeType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2025-2"


class ForecastChangeIndicatorType(Enum):
    """
    Change qualifier of a trend-type forecast or an aerodrome forecast.

    Defined in the Manual on Codes (WMO No. 306), Vol I.1; FM-15 METAR, FM-16 SPECI and FM-51 TAF. Also see WMO No.
    306 Vol I.2 Part B FM 94 BUFR Code table 0 08 016 'Change qualifier of a trend forecast or an aerodrome
    forecast'.

    Properties
    ----------
    BECOMING
        When the change is forecast to commence at the beginning of the forecast period and be completed by the end
        of that period, or when the change is forecast to occur within the forecast period but the time of the change
        is uncertain (possibly shortly after the beginning of the forecast period, or midway or near the end of that
        period), the change is indicated by only the change indicator BECMG.
    TEMPORARY_FLUCTUATIONS
        The change indicator TEMPO is used to describe expected temporary fluctuations to meteorological conditions
        which reach or pass specified threshold criteria and last for a period of less than one hour in each instance
        and in the aggregate cover less than half of the forecast period during which the fluctuations are expected
        to occur.
    """

    BECOMING = "BECOMING"
    TEMPORARY_FLUCTUATIONS = "TEMPORARY_FLUCTUATIONS"


class TrendForecastTimeIndicatorType(Enum):
    """
    Time indicators for trend forecast conditions.

    These are equivalent to the traditional FM, TL, and AT codes.

    Properties
    ----------
    AT
        This trend forecast specifies a time instant at which time conditions occur (AT)
    UNTIL
        This trend forecast specifies a time period which commences at the beginning of the trend forecast period and
        is completed by a specified time (TL)
    FROM
        This trend forecast specifies a time period which commences at a specified time and is completed by the end
        of the trend forecast period (FM)
    FROM_UNTIL
        This trend forecast specifies a time period which commences at a specified time and is completed by another
        specified time (FM and TL)
    """

    AT = "AT"
    UNTIL = "UNTIL"
    FROM = "FROM"
    FROM_UNTIL = "FROM_UNTIL"


class VisualRangeTendencyType(Enum):
    """
    The tendency of visual range (e.g., upward, downward).

    Defined for the purposes of aviation meteorology reporting of the visual range on runways (ICAO Annex 3 and
    PANS-MET (Doc 10157)). If the [runway] visual range (RVR) values during the 10-minute period preceding the
    nominal observation time show a distinct upward or downward tendency such that the mean during the first five
    minutes varies by 100 metres or more from the mean in the second five minutes of the period, an UPWARD [U] or
    DOWNWARD [D] tendency is recorded. When no distinct change in RVR is observed, NO CHANGE [N] is recorded. When
    it is not possible to determine the tendency, MISSING VALUE is recorded. See the Manual on Codes (WMO No. 306)
    Vol I.2 FM 94 BUFR Code table 0 20 018 "Tendency of runway visual range".

    Properties
    ----------
    UPWARD
        Upward (increasing) tendency
    NO_CHANGE
        No distinct change
    DOWNWARD
        Downward (decreasing) tendency
    MISSING_VALUE
        Missing value
    """

    UPWARD = "UPWARD"
    NO_CHANGE = "NO_CHANGE"
    DOWNWARD = "DOWNWARD"
    MISSING_VALUE = "MISSING_VALUE"


class AerodromeCloudType(BaseModel):
    """
    Parameters
    ----------
    vertical_visibility
        The reported vertical visibility.  Vertical visibility is defined as the vertical visual range into an
        obscuring medium. Measured vertical visibility shall be reported in either two units of measures: meters
        ("m") or feet ("[ft_i]"). Note: vertical visibility is only reported in aviation-specific WMO Code-forms
        (FM-15 METAR, FM-16 SPECI and FM-51 TAF) thus prevailing visibility is considered to be an aviation-specific
        quantity. When the sky is obscured and the value of the vertical visibility cannot be determined by the
        automatic observing system due to a temporary failure of the system/sensor ("VV///") the vertical visibility
        is missing with a nil reason of notObservable
    layer
    extension
        Extension block for optional and/or additional parameters for element AerodromeCloud
    """

    model_config = ConfigDict(defer_build=True)
    vertical_visibility: None | LengthWithNilReasonType = field(
        default=None,
        metadata={
            "name": "verticalVisibility",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    layer: list[AerodromeCloudType.Layer] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 4,
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )

    class Layer(CloudLayerPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )


class AerodromeHorizontalVisibilityType(BaseModel):
    """
    Parameters
    ----------
    prevailing_visibility
        The reported prevailing horizontal visibility at the surface that is representative of the aerodrome.
        Measured prevailing horizontal visibility shall be reported in meters ("m") only. The greatest visibility
        value, observed in accordance with the definition of "visibility", which is reached within at least half the
        horizon circle or within at least half of the surface of the aerodrome. These areas could comprise contiguous
        or non-contiguous sectors. Note: This value may be assessed by human observation and/or instrumented systems.
        When instruments are installed, they are used to obtain the best estimate of the prevailing visibility. To
        report a prevailing visibility of at least 10000 meters, prevailing visibility is reported as 10000 meters
        and the prevailing visibility operator is reported as "above". See ICAO PANS-MET (Doc 10157) Section
        2.2.2.4.4.
    prevailing_visibility_operator
        The reported relational operator for the prevailing horizontal visibility.  When reported, this operator is
        reported in conjunction with prevailing visibility. To report a prevailing visibility of at least 10000
        meters, prevailing visibility is reported as 10000 meters and the operator is reported as "above". When no
        operator is reported, prevailing visibility represents an exact value with identical semantics to other
        measured quantities
    minimum_visibility
        The minimum observed visibility. Measured minimum visibility shall be reported in meters ("m") only. ICAO
        PANS-MET Section 2.2.2.4.4: "When the visibility is not the same in different directions and a) when the
        lowest visibility is different from the prevailing visibility, and 1) less than 1500 m or 2) less than 50
        percent of the prevailing visibility and less than 5000 m; the lowest visibility observed should also be
        reported and,when possible, its general direction in relation to the aerodrome reference point indicated by
        reference to one of the eight points of the compass. If the lowest visibility is observed in more than one
        direction, then the most operationally significant direction should be reported; and b) when the visibility
        is fluctuating rapidly, and the prevailing visibility cannot be determined, only the lowest visibility should
        be reported, with no indication of direction."
    minimum_visibility_direction
        The direction of the minimum visibility relative to the reporting station.  This is optional in cases where
        minimum visibility is reported but the visibility is fluctuating rapidly.  Minimum visibility is reported in
        cardinal and inter-cardinal directions (N, NE, E, SE, S, SW, W, and NW) Direction of minimum visibility shall
        be given in degrees from true North. Plane angle unit of measure (uom) is "deg".
    extension
        Extension block for optional and/or additional parameters for element AerodromeHorizontalVisibility
    """

    model_config = ConfigDict(defer_build=True)
    prevailing_visibility: None | DistanceWithNilReasonType = field(
        metadata={
            "name": "prevailingVisibility",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    prevailing_visibility_operator: None | RelationalOperatorType = field(
        default=None,
        metadata={
            "name": "prevailingVisibilityOperator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    minimum_visibility: None | DistanceWithNilReasonType = field(
        default=None,
        metadata={
            "name": "minimumVisibility",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    minimum_visibility_direction: None | AngleWithNilReasonType = field(
        default=None,
        metadata={
            "name": "minimumVisibilityDirection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class AerodromePresentWeatherType(ReferenceType):
    """
    The present weather observed at, or in near vicinity of, an aerodrome.

    Only a specific set of weather phenomenon are reported within aviation meteorology as defined in ICAO Annex 3
    and PANS-MET (Doc 10157). This codelist is specifically defined for aviation purposes as defined in ICAO
    PANS-MET. A superset of definitions are defined in the Manual on Codes (WMO No. 306), Vol I.1 Code table 4678
    "Significant weather phenomena".
    """

    model_config = ConfigDict(defer_build=True)


class AerodromeRecentWeatherType(ReferenceType):
    """
    Weather phenomenon of operational significance to aviation observed during the period since the last routine
    report, or last hour, whichever is shorter, but not at the time of observation.

    Only a specific set of weather phenomenon are reported within aviation meteorology as defined in ICAO Annex 3
    and PANS-MET (Doc 10157). This codelist is specifically defined for aviation purposes as defined in PANS-MET. A
    superset of definitions are defined in the Manual on Codes (WMO No. 306), Vol I.1 Code table 4678 "Significant
    weather phenomena".
    """

    model_config = ConfigDict(defer_build=True)


class AerodromeRunwayVisualRangeType(BaseModel):
    """
    Parameters
    ----------
    runway
        The runway to which reported runway visual range information applies
    mean_rvr
        The mean recent runway visual range value observed. This mean represents the 10 minute average for observed
        RVR except when the 10-minute period immediately preceding the observation includes a marked discontinuity in
        runway visual range values, only those values occurring after the discontinuity is used for obtaining mean
        values. Mean runway visual range distance shall be reported in meters ("m"). To report a mean RVR of at least
        2000 meters, mean RVR is reported as 2000 meters and the operator is reported as "above" See ICAO PANS-MET
        (Doc 10157) Section 2.2.3.6.
    mean_rvroperator
        The reported relational operator for the mean RVR. When reported, this operator is reported in conjunction
        with mean RVR. To report a mean RVR of at least 2000 metres, mean RVR is reported as 2000 metres and the
        operator is reported as "above".  To report a mean RVR of less than 50 metres, mean RVR is reported as 50
        metres and the operator is reported as "below".  When no operator is reported, mean RVR represents an exact
        value with identical semantics to other measured quantities
    extension
        Extension block for optional and/or additional parameters for element AerodromeRunwayVisualRange
    past_tendency
        The runway visual range tendency (up, down, no_change). If the runway visual range values during the
        10-minute period have shown a distinct tendency, such that the mean during the first 5 minutes varies by 100
        m or more from the mean during the second 5 minutes of the period, this should be indicated. When the
        variation of the runway visual range values shows an upward or downward tendency, this should be indicated by
        "Up" or "Down", respectively. In circumstances when actual fluctuations during the 10-minute period show no
        distinct tendency, this should be indicated using "No Change". When indications of tendency are not
        available, no information should be reported. See ICAO PANS-MET (Doc 10157) Section 2.2.3.6.6.
    """

    model_config = ConfigDict(defer_build=True)
    runway: None | RunwayDirectionPropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    mean_rvr: None | DistanceWithNilReasonType = field(
        metadata={
            "name": "meanRVR",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    mean_rvroperator: None | RelationalOperatorType = field(
        default=None,
        metadata={
            "name": "meanRVROperator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    past_tendency: None | VisualRangeTendencyType = field(
        default=None,
        metadata={
            "name": "pastTendency",
            "type": "Attribute",
        },
    )


class AerodromeSurfaceWindType(BaseModel):
    """
    Parameters
    ----------
    mean_wind_direction
        The observed average wind direction from which the wind is blowing over the past ten minutes.  Not reported
        when winds are variable. Wind direction shall be given in degrees from true North. Plane angle unit of
        measure (uom) is "deg".  A true north wind is indicated with a direction of 360. Calm wind is indicated with
        a direction of 0.
    mean_wind_speed
        The average observed wind speed over the past ten minutes See ICAO PANS-MET (Doc 10157) Section 2.2.1.5.2 a).
        Wind speeds shall be provided in either two units of measures: "m/s" or "[kn_i]" (knot).
    mean_wind_speed_operator
        Indication that the mean wind speed is above or below the reported value.  To report a wind speed of at least
        49 meters per second, wind speed is reported as 49 meters per second and the operator is reported as "above".
        When no operator is reported, wind speed is an exact value with identical semantics to other measured
        quantities.
    wind_gust_speed
        Variations from the mean wind speed (gusts) during the past 10 minutes. See ICAO PANS-MET (Doc 10157) Section
        2.2.1.5.2 c). Wind gusts shall be provided in either two units of measures: "m/s" or "[kn_i]" (knot).
    wind_gust_speed_operator
        Indication that the wind gust speed is above or below the reported value.  To report a wind gust speed of at
        least 49 meters per second, wind gust speed is reported as 49 meters per second and the operator is reported
        as "above". When no operator is reported, wind gust speed is an exact value with identical semantics to other
        measured quantities.
    extreme_clockwise_wind_direction
        The extreme clockwise direction from which the wind has varied, inclusive. This corresponds to the dxdxdx
        part of the reported variation dndndnVdxdxdx in TAC. See ICAO PANS-MET (Doc 10157) Section 2.2.1.5.2 b) 1)
    extreme_counter_clockwise_wind_direction
        The extreme counter-clockwise direction from which the wind has varied, inclusive. This corresponds to the
        dndndn part of the reported variation dndndnVdxdxdx in TAC. See ICAO PANS-MET (Doc 10157) Section 2.2.1.5.2
        b) 1)
    extension
        Extension block for optional and/or additional parameters for element AerodromeSurfaceWind
    variable_wind_direction
        When true, indicates that the wind direction is variable.  A wind direction value may still be reported
    """

    model_config = ConfigDict(defer_build=True)
    mean_wind_direction: None | AngleWithNilReasonType = field(
        default=None,
        metadata={
            "name": "meanWindDirection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    mean_wind_speed: None | VelocityWithNilReasonType = field(
        metadata={
            "name": "meanWindSpeed",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    mean_wind_speed_operator: None | RelationalOperatorType = field(
        default=None,
        metadata={
            "name": "meanWindSpeedOperator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    wind_gust_speed: None | VelocityWithNilReasonType = field(
        default=None,
        metadata={
            "name": "windGustSpeed",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    wind_gust_speed_operator: None | RelationalOperatorType = field(
        default=None,
        metadata={
            "name": "windGustSpeedOperator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extreme_clockwise_wind_direction: None | AngleWithNilReasonType = field(
        default=None,
        metadata={
            "name": "extremeClockwiseWindDirection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extreme_counter_clockwise_wind_direction: None | AngleWithNilReasonType = field(
        default=None,
        metadata={
            "name": "extremeCounterClockwiseWindDirection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    variable_wind_direction: None | bool = field(
        default=None,
        metadata={
            "name": "variableWindDirection",
            "type": "Attribute",
        },
    )


class AerodromeWindShearType(BaseModel):
    """
    Parameters
    ----------
    runway
        The specific runway(s) affected by wind shear at this aerodrome. No specific runways are reported when all
        runways are affected by wind shear
    extension
        Extension block for optional and/or additional parameters for element AerodromeWindShear
    all_runways
        When true, all runways are observed to have wind shear
    """

    model_config = ConfigDict(defer_build=True)
    runway: list[RunwayDirectionPropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    all_runways: None | bool = field(
        default=None,
        metadata={
            "name": "allRunways",
            "type": "Attribute",
        },
    )


class MeteorologicalAerodromeTrendForecastType(AbstractGmltype):
    """
    Parameters
    ----------
    phenomenon_time
        The time at which meteorological phenomena occur
    time_indicator
        The human-readable time indicator for this trend forecast.  This should match the time period or time instant
        reported in the phenomenon time
    prevailing_visibility
        The prevailing horizontal visibility reported in a trend forecast. Prevailing horizontal visibility shall be
        reported in meters ("m").
    prevailing_visibility_operator
        The reported relational operator for the prevailing horizontal visibility.  When reported, this operator is
        reported in conjunction with prevailing visibility. To report a prevailing visibility of at least 10000
        meters, prevailing visibility is reported as 10000 meters and the operator is reported as "above". When no
        operator is reported, prevailing visibility represents an exact value with identical semantics to other
        measured quantities
    surface_wind
        Forecast of surface wind.
    weather
        Forecast of weather phenomena.
    cloud
        Forecast of cloud.
    extension
        Extension block for optional and/or additional parameters for element MeteorologicalAerodromeTrendForecast
    change_indicator
        The change indicator for this trend forecast - becoming, temporary conditions, or no significant change
    cloud_and_visibility_ok
        When true, indicates that the following conditions occur simultaneously at the time of forecast (also know as
        "CAVOK"): a) visibility, 10km or more, and the lowest visibility is not reported b) no cloud of operational
        significance c) no weather of significance to aviation Information on visibility, runway visual range,
        present weather and cloud amount, cloud type and height of cloud base shall not be reported.  See ICAO PANS-
        MET (Doc 10157) Section 2.2.
    """

    model_config = ConfigDict(defer_build=True)
    phenomenon_time: AbstractTimeObjectPropertyType = field(
        metadata={
            "name": "phenomenonTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    time_indicator: None | TrendForecastTimeIndicatorType = field(
        default=None,
        metadata={
            "name": "timeIndicator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    prevailing_visibility: None | LengthType = field(
        default=None,
        metadata={
            "name": "prevailingVisibility",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    prevailing_visibility_operator: None | RelationalOperatorType = field(
        default=None,
        metadata={
            "name": "prevailingVisibilityOperator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    surface_wind: None | AerodromeSurfaceWindTrendForecastPropertyType = field(
        default=None,
        metadata={
            "name": "surfaceWind",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    weather: list[AerodromeForecastWeatherType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 3,
            "nillable": True,
        },
    )
    cloud: None | AerodromeCloudForecastPropertyType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    change_indicator: ForecastChangeIndicatorType = field(
        metadata={
            "name": "changeIndicator",
            "type": "Attribute",
        }
    )
    cloud_and_visibility_ok: None | bool = field(
        default=None,
        metadata={
            "name": "cloudAndVisibilityOK",
            "type": "Attribute",
        },
    )


class SeaSurfaceStateType(ReferenceType):
    """
    Categorical assessment of sea surface state (or other large open body of water) based on height of waves.

    Height in metres : Category - 0 metres : Calm (glassy) - 0-0.1 metres : Calm (rippled) - 0.1-0.5 metres : Smooth
    - 0.5-1.25 metres : Slight - 1.25-2.5 metres : Moderate - 2.5-4 metres : Rough - 4-6 metres : Very rough - 6-9
    metres : High - 9-14 metres : Very high - &gt;14 metres : Phenomenal See the Manual on Codes (WMO No. 306), Vol
    I.1 Code table 3700 "State of the sea" and WMO No. 306 Vol I.2 FM 94 BUFR Code table 0 22 061 "State of the
    sea".
    """

    model_config = ConfigDict(defer_build=True)


class AerodromeCloud(AerodromeCloudType):
    """
    An aggregation of observed cloud conditions typically reported together at an aerodrome, including cloud types,
    cloud layers, and vertical visibility.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeHorizontalVisibility(AerodromeHorizontalVisibilityType):
    """
    An aggregation of horizontal visibility conditions typically reported together at an aerodrome, including the
    prevailing visibility and minimum visibility.

    Direction of minimum visibility shall be given in degrees from true North. Plane angle unit of measure (uom) is
    "deg". Measured prevailing and minimum horizontal visibility, if present, shall be reported in meters ("m")
    only.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromePresentWeather(AerodromePresentWeatherType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeRecentWeather(AerodromeRecentWeatherType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeRunwayVisualRange(AerodromeRunwayVisualRangeType):
    """
    An aggregation of runway visual range conditions for a single runway, typically reported together at an
    aerodrome.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeSeaConditionType(BaseModel):
    """
    Parameters
    ----------
    sea_surface_temperature
        The sea-surface temperature observed by aeronautical meteorological stations established on offshore
        structures in support of helicopter operations. The term sea surface temperature is generally meant to be
        representative of the upper few meters of the ocean as opposed to the skin temperature, which is the
        temperature of the upper few centimeters. Temperatures shall be reported in degrees Celsius ("Cel"). See ICAO
        PAN-MET (Doc 10157) Section 2.2.8.1.5.
    significant_wave_height
        The significant wave height observed. Significant wave height shall be reported in meters ("m").
    sea_state
        The state of the sea observed by aeronautical meteorological stations established on offshore structures in
        support of helicopter operations See ICAO PANS-MET (Doc 10157) Section 2.2.8.1.5 and the Manual on Codes (WMO
        No.306), Vol. I.1 Table 3700.
    extension
        Extension block for optional and/or additional parameters for element AerodromeSeaCondition
    """

    model_config = ConfigDict(defer_build=True)
    sea_surface_temperature: None | MeasureWithNilReasonType = field(
        metadata={
            "name": "seaSurfaceTemperature",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    significant_wave_height: None | DistanceWithNilReasonType = field(
        default=None,
        metadata={
            "name": "significantWaveHeight",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    sea_state: None | SeaSurfaceStateType = field(
        default=None,
        metadata={
            "name": "seaState",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class AerodromeSurfaceWind(AerodromeSurfaceWindType):
    """
    An aggregation of surface wind conditions typically reported together at an aerodrome, including wind direction
    information, wind speed, and wind gusts.

    Wind direction is reported according to ICAO PANS-MET (Doc 10157) Section 2.2.1.5.2 b): "variations from the
    mean wind direction during the past 10 minutes shall be reported as follows, if the total variation is 60° or
    more: 1) when the total variation is 60° or more and less than 180° and the wind speed is 1.5 m/s (3 kt) or
    more, such directional variations shall be reported as the two extreme directions between which the surface wind
    has varied; 2) when the total variation is 60° or more and less than 180° and the wind speed is less than 1.5
    m/s (3 kt), the wind direction shall be reported as variable with no mean wind direction; or 3) when the total
    variation is 180° or more, the wind direction shall be reported as variable with no mean wind direction" Wind
    direction shall be given in degrees from true North. Plane angle unit of measure (uom) is "deg". A true north
    wind is indicated with a direction of 360. Calm wind is indicated with a direction of 0. Wind speeds and gusts,
    if present, shall be provided in either two units of measures: "m/s" or "[kn_i]" (knot).
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeWindShear(AerodromeWindShearType):
    """
    An aggregation of wind shear conditions typically reported together at an aerodrome, including the set of
    affected runways.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class MeteorologicalAerodromeTrendForecast(MeteorologicalAerodromeTrendForecastType):
    """
    Meteorological conditions for trend forecasting at an aerodrome.

    This class is also related but not identical to MeteorologicalAerodromeForecast which is reported on a TAF -
    conditions reported in trend forecasts in METAR/SPECI differ from forecast groups in a TAF. When no clouds of
    operational significance or no weather of operational significance is predicted, the
    NothingOfOperationalSignificance nilReason should be used for the cloud or presentWeather association. When no
    clouds were detected by the automatic observing system, the NotDetectedByAutoSystem nilReason should be used for
    the cloud association.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SeaSurfaceState(SeaSurfaceStateType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeCloudPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_cloud: AerodromeCloud = field(
        metadata={
            "name": "AerodromeCloud",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class AerodromeHorizontalVisibilityPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_horizontal_visibility: AerodromeHorizontalVisibility = field(
        metadata={
            "name": "AerodromeHorizontalVisibility",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class AerodromeRunwayVisualRangePropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_runway_visual_range: AerodromeRunwayVisualRange = field(
        metadata={
            "name": "AerodromeRunwayVisualRange",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class AerodromeSeaCondition(AerodromeSeaConditionType):
    """
    An aggregation of sea state conditions typically reported together at an aerodrome.

    This includes information on sea-surface temperature and either the state of the sea or significant wave height
    from aeronautical meteorological stations established on offshore structures in support of helicopter
    operations.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class AerodromeSurfaceWindPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_surface_wind: AerodromeSurfaceWind = field(
        metadata={
            "name": "AerodromeSurfaceWind",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class AerodromeWindShearPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_wind_shear: AerodromeWindShear = field(
        metadata={
            "name": "AerodromeWindShear",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class MeteorologicalAerodromeTrendForecastPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    meteorological_aerodrome_trend_forecast: (
        None | MeteorologicalAerodromeTrendForecast
    ) = field(
        default=None,
        metadata={
            "name": "MeteorologicalAerodromeTrendForecast",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class AerodromeSeaConditionPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    aerodrome_sea_condition: AerodromeSeaCondition = field(
        metadata={
            "name": "AerodromeSeaCondition",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class MeteorologicalAerodromeObservationType(AbstractGmltype):
    """
    Parameters
    ----------
    air_temperature
        The observed air temperature.  This is the temperature indicated by a thermometer exposed to the air in a
        place sheltered from direct solar radiation. Measured air temperature shall be given in degrees Celsius
        ("Cel").  It should also be provided in tenths of a degree Celsius.
    dewpoint_temperature
        The observed dew point temperature.  This is the temperature to which a given air parcel must be cooled at
        constant pressure and constant water vapor content in order for saturation to occur. Measured dew-point
        temperature shall be given in degrees Celsius ("Cel").  It should also be provided in tenths of a degree
        Celsius.
    qnh
        The observed QNH altimeter setting. Altitude setting (also known as QNH) is defined as barometric pressure
        adjusted to sea level. It is a pressure setting used by pilots, air traffic control (ATC), and low frequency
        weather beacons to refer to the barometric setting which, when set on an aircraft's altimeter, will cause the
        altimeter to read altitude above mean sea level within a certain defined region. Measured altimeter setting
        shall be given in hectoPascals ("hPa").
    surface_wind
        Representative surface wind observations.
    visibility
        Visibility reported as prevailing visibility or the lowest visibility as appropriate.
    rvr
        RVR conditions are required if horizontal visibility or RVR is less than 1500 meters
    present_weather
        When observed, between one and three present weather conditions When present weather cannot be observed by
        the automatic observing system due to a temporary failure of the system/sensor ("//") the present weather is
        missing with a nil reason of notObservable
    cloud
        When no clouds are detected by the automatic observing system, it should be indicated by a missing cloud
        group with a nil reason of notDetectedByAutoSystem ("NCD" from TAC). When there are no clouds of operational
        significance and no restriction on vertical visibility and “CAVOK” is not appropriate ("NSC") it should be
        indicated by a missing cloud group with a nil reason of nothingOfOperationalSignificance
    recent_weather
        Recent weather is one of the recent weather phenomena to be reported as supplementary information.
    wind_shear
        Wind shear is one of the recent weather phenomena to be reported as supplementary information.
    sea_condition
        Sea surface temperature and state of the sea or significant wave height are recent weather phenomena to be
        reported as supplementary information.
    extension
        Extension block for optional and/or additional parameters for element MeteorologicalAerodromeObservation
    cloud_and_visibility_ok
        When true, indicates that the following conditions occur simultaneously at the time of observation (also know
        as "CAVOK"): a) visibility, 10km or more, and the lowest visibility is not reported b) no cloud of
        operational significance c) no weather of significance to aviation Information on visibility, runway visual
        range, present weather and cloud amount, cloud type and height of cloud base shall not be reported.  See ICAO
        PANS-MET (Doc 10157) Section 2.2.
    """

    model_config = ConfigDict(defer_build=True)
    air_temperature: None | MeasureWithNilReasonType = field(
        metadata={
            "name": "airTemperature",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    dewpoint_temperature: None | MeasureWithNilReasonType = field(
        metadata={
            "name": "dewpointTemperature",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    qnh: None | MeasureWithNilReasonType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    surface_wind: None | MeteorologicalAerodromeObservationType.SurfaceWind = field(
        metadata={
            "name": "surfaceWind",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    visibility: None | MeteorologicalAerodromeObservationType.Visibility = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    rvr: list[MeteorologicalAerodromeObservationType.Rvr] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    present_weather: list[AerodromePresentWeatherType] = field(
        default_factory=list,
        metadata={
            "name": "presentWeather",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 3,
            "nillable": True,
        },
    )
    cloud: None | MeteorologicalAerodromeObservationType.Cloud = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    recent_weather: list[AerodromeRecentWeatherType] = field(
        default_factory=list,
        metadata={
            "name": "recentWeather",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 3,
            "nillable": True,
        },
    )
    wind_shear: None | MeteorologicalAerodromeObservationType.WindShear = field(
        default=None,
        metadata={
            "name": "windShear",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    sea_condition: None | MeteorologicalAerodromeObservationType.SeaCondition = field(
        default=None,
        metadata={
            "name": "seaCondition",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    cloud_and_visibility_ok: bool = field(
        metadata={
            "name": "cloudAndVisibilityOK",
            "type": "Attribute",
        }
    )

    class SurfaceWind(AerodromeSurfaceWindPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )

    class Visibility(AerodromeHorizontalVisibilityPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )

    class Rvr(AerodromeRunwayVisualRangePropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )

    class Cloud(AerodromeCloudPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )

    class WindShear(AerodromeWindShearPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )

    class SeaCondition(AerodromeSeaConditionPropertyType):
        model_config = ConfigDict(defer_build=True)
        nil_reason: None | str | NilReasonEnumerationValue = field(
            default=None,
            metadata={
                "name": "nilReason",
                "type": "Attribute",
                "pattern": r"other:\w{2,}",
            },
        )


class MeteorologicalAerodromeObservation(MeteorologicalAerodromeObservationType):
    """
    Meteorological conditions observed at an aerodrome.

    When no clouds of operational significance or no weather of operational significance is observed, the
    NothingOfOperationalSignificance nilReason is used for the cloud or presentWeather association. When no clouds
    were detected by the automatic observing system, the NotDetectedByAutoSystem nilReason is used for the cloud
    association.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class MeteorologicalAerodromeObservationPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    meteorological_aerodrome_observation: None | MeteorologicalAerodromeObservation = (
        field(
            default=None,
            metadata={
                "name": "MeteorologicalAerodromeObservation",
                "type": "Element",
                "namespace": "http://icao.int/iwxxm/2025-2",
            },
        )
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class MeteorologicalAerodromeObservationReportType(ReportType):
    """
    Parameters
    ----------
    issue_time
        The time at which this report was issued
    aerodrome
        The aerodrome location for this report
    observation_time
        The time at which phenomena were observed.  This may differ from the times reported for forecast conditions
    observation
        The observation which resulted in the current meteorological conditions at an aerodrome
    trend_forecast
        The process that results in a trend forecast.  When no change is expected to occur during a forecast period
        ("NOSIG") this is indicated by a single missing trend forecast with a nil reason of noSignificantChange
    automated_station
        When true, this report was reported by an automated station.
    """

    model_config = ConfigDict(defer_build=True)
    issue_time: TimeInstantPropertyType = field(
        metadata={
            "name": "issueTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    aerodrome: AirportHeliportPropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    observation_time: TimeInstantPropertyType = field(
        metadata={
            "name": "observationTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    observation: None | MeteorologicalAerodromeObservationPropertyType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    trend_forecast: list[MeteorologicalAerodromeTrendForecastPropertyType] = field(
        default_factory=list,
        metadata={
            "name": "trendForecast",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    automated_station: None | bool = field(
        default=None,
        metadata={
            "name": "automatedStation",
            "type": "Attribute",
        },
    )


class Metartype(MeteorologicalAerodromeObservationReportType):
    """
    Parameters
    ----------
    extension
        Extension block for optional and/or additional parameters for element METAR
    """

    class Meta:
        name = "METARType"

    model_config = ConfigDict(defer_build=True)
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class MeteorologicalAerodromeObservationReport(
    MeteorologicalAerodromeObservationReportType
):
    """
    A report of observed and trend forecast weather phenomenon from the surface near an aerodrome.

    This is a shared superclass for METAR and SPECI reports, which have identical reported information.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class Specitype(MeteorologicalAerodromeObservationReportType):
    """
    Parameters
    ----------
    extension
        Extension block for optional and/or additional parameters for element SPECI
    """

    class Meta:
        name = "SPECIType"

    model_config = ConfigDict(defer_build=True)
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class Metar(Metartype):
    """
    A routine observation made at an aerodrome throughout the day.

    METAR observations are made (and distributed) at intervals of one hour or, if so determined by regional air
    navigation agreement, at intervals of one half-hour. The information contained in METAR and SPECI is identical.
    SPECI is issued when conditions merit a non-routine report on conditions at an aerodrome. METARs are a routine
    report produced for dissemination beyond the aerodrome of origin, and are mainly intended for flight planning,
    VOLMET broadcasts and D-VOLMET. See ICAO Annex 3 and PANS-MET (Doc 10157).
    """

    class Meta:
        name = "METAR"
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class Speci(Specitype):
    """
    A special (i.e., non-routine) observation made at an aerodrome as needed.

    SPECI observations are made (and distributed) in accordance with criteria established by the meteorological
    authority, in consultation with the appropriate ATS authority, operators and others concerned. The information
    contained in METAR and SPECI is identical. SPECI is issued when conditions merit a non-routine report on
    conditions at an aerodrome. SPECI reports are used for dissemination beyond the aerodrome of origin (mainly
    intended for flight planning, VOLMET broadcasts and D-VOLMET) unless METAR are issued at half-hourly intervals.
    SPECI is issued following the resumption of the issuance of METAR, as necessary, at aerodromes that are not
    operational throughout 24 hours. See ICAO Annex 3 and PANS-MET (Doc 10157).
    """

    class Meta:
        name = "SPECI"
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class MetarpropertyType(BaseModel):
    class Meta:
        name = "METARPropertyType"

    model_config = ConfigDict(defer_build=True)
    metar: None | Metar = field(
        default=None,
        metadata={
            "name": "METAR",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class MeteorologicalAerodromeObservationReportPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    metar: None | Metar = field(
        default=None,
        metadata={
            "name": "METAR",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    speci: None | Speci = field(
        default=None,
        metadata={
            "name": "SPECI",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpecipropertyType(BaseModel):
    class Meta:
        name = "SPECIPropertyType"

    model_config = ConfigDict(defer_build=True)
    speci: None | Speci = field(
        default=None,
        metadata={
            "name": "SPECI",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
