"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from .common import (
    AbstractTimeObjectPropertyType,
    AirspaceVolumePropertyType,
    ExtensionType,
    ReportType,
    StringWithNilReasonType,
    TimeIndicatorType,
    UnitPropertyType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.feature import AbstractFeatureType
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.gml_base import (
    AbstractGmltype,
    ReferenceType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.temporal import TimeInstantPropertyType
from .xlink import (
    ActuateType,
    ShowType,
    TypeType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2025-2"


class SpaceWeatherEffectType(Enum):
    """
    Effect of the space weather phenomena.

    Properties
    ----------
    HF_COM
        High frequency communications.
    SATCOM
        Satellite communications.
    GNSS
        GNSS-based navigation and surveillance.
    RADIATION
        Radiation dose rates on polar flights.
    """

    HF_COM = "HF_COM"
    SATCOM = "SATCOM"
    GNSS = "GNSS"
    RADIATION = "RADIATION"


class SpaceWeatherIntensityType(Enum):
    """
    Intensity of the space weather phenomena.

    Properties
    ----------
    MOD
        Moderate.
    SEV
        Severe.
    """

    MOD = "MOD"
    SEV = "SEV"


class SpaceWeatherLocationType(ReferenceType):
    """
    Coverage affected by space weather phenomenon - HNH (high northern hemisphere) - MNH (middle northern
    hemisphere) - EQN (equatorial latitudes northern hemisphere) - EQS (equatorial latitudes southern hemisphere) -
    MSH (middle latitudes southern hemisphere) - HSH (high latitudes southern hemisphere) - DAYSIDE (Day side) -
    NIGHTSIDE (Night side).
    """

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherLocation(SpaceWeatherLocationType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherRegionType(AbstractGmltype):
    """
    Parameters
    ----------
    location
        The geographic location at which space weather phenomena occur
    location_indicator
        The geographic area code, such as high northern latitudes
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherRegion
    """

    model_config = ConfigDict(defer_build=True)
    location: AirspaceVolumePropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    location_indicator: list[SpaceWeatherLocationType] = field(
        default_factory=list,
        metadata={
            "name": "locationIndicator",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "min_occurs": 1,
            "max_occurs": 6,
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class SpaceWeatherRegion(SpaceWeatherRegionType):
    """
    Affected region described in coordinates and textual description (if applicable), as well as altitude (radiation
    events only).
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherRegionPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_region: None | SpaceWeatherRegion = field(
        default=None,
        metadata={
            "name": "SpaceWeatherRegion",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpaceWeatherIntensityAndRegionType(AbstractGmltype):
    """
    Parameters
    ----------
    intensity
        Intensity of the space weather phenomena.
    region
        Region affected by the space weather phenomena.
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherIntensityAndRegion
    """

    model_config = ConfigDict(defer_build=True)
    intensity: SpaceWeatherIntensityType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    region: list[SpaceWeatherRegionPropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "min_occurs": 1,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class SpaceWeatherIntensityAndRegion(SpaceWeatherIntensityAndRegionType):
    """
    Container of space weather intensity and affected region(s).
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherIntensityAndRegionPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_intensity_and_region: None | SpaceWeatherIntensityAndRegion = field(
        default=None,
        metadata={
            "name": "SpaceWeatherIntensityAndRegion",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpaceWeatherAnalysisType(AbstractFeatureType):
    """
    Parameters
    ----------
    phenomenon_time
        The time at which meteorological phenomena occur
    intensity_and_region
        Container of intensity of the space weather phenomena and affected region(s)
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherAnalysis
    time_indicator
        Indicator of observed or forecast conditions
    """

    model_config = ConfigDict(defer_build=True)
    phenomenon_time: AbstractTimeObjectPropertyType = field(
        metadata={
            "name": "phenomenonTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    intensity_and_region: list[SpaceWeatherIntensityAndRegionPropertyType] = field(
        default_factory=list,
        metadata={
            "name": "intensityAndRegion",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "min_occurs": 1,
            "nillable": True,
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    time_indicator: TimeIndicatorType = field(
        metadata={
            "name": "timeIndicator",
            "type": "Attribute",
        }
    )


class SpaceWeatherAnalysis(SpaceWeatherAnalysisType):
    """
    Observed or forecast space weather phenomena.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherAnalysisPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_analysis: None | SpaceWeatherAnalysis = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAnalysis",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class SpaceWeatherAdvisoryType(ReportType):
    """
    Parameters
    ----------
    issue_time
        The time at which this report was issued
    issuing_space_weather_centre
        The issuing space weather centre (SWXC)
    advisory_number
        Advisory number: four digit year and unique message number.  Example "2018/1"
    replaced_advisory_number
        The number of the advisory being replaced.  Example "2018/1"
    effect
        Space weather effect.
    analysis
        Observed and forecast space weather information.  Analyses should be reported in the order in which they
        occur, starting with the initial observed/forecast conditions and proceeding through each subsequent forecast
        to the end of the period
    remarks
        Remarks, as necessary. When the remark is nil, it should be indicated by a missing remarks with a nil reason
        of 'inapplicable'
    next_advisory_time
        The time at which the next advisory will be issued Use attribute indeterminatePosition to element
        timePosition to indicate if the actual temporal position is before or after the specified value. When no
        subsequent advisory is expected to be issued it should be indicated by a missing expected advisory time with
        a nil reason of 'inapplicable'
    extension
        Extension block for optional and/or additional parameters for element SpaceWeatherAdvisory
    """

    model_config = ConfigDict(defer_build=True)
    issue_time: TimeInstantPropertyType = field(
        metadata={
            "name": "issueTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    issuing_space_weather_centre: UnitPropertyType = field(
        metadata={
            "name": "issuingSpaceWeatherCentre",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    advisory_number: None | StringWithNilReasonType = field(
        default=None,
        metadata={
            "name": "advisoryNumber",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    replaced_advisory_number: list[str] = field(
        default_factory=list,
        metadata={
            "name": "replacedAdvisoryNumber",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 4,
        },
    )
    effect: list[SpaceWeatherEffectType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    analysis: list[SpaceWeatherAnalysisPropertyType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "max_occurs": 5,
        },
    )
    remarks: None | StringWithNilReasonType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    next_advisory_time: None | TimeInstantPropertyType = field(
        default=None,
        metadata={
            "name": "nextAdvisoryTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class SpaceWeatherAdvisory(SpaceWeatherAdvisoryType):
    """
    An advisory of space weather conditions of significance to aviation as represented in ICAO Annex 3 and PANS-MET
    (Doc 10157).

    Volcanic ash advisories are issued by space weather centres (SWXCs).
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class SpaceWeatherAdvisoryPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    space_weather_advisory: None | SpaceWeatherAdvisory = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAdvisory",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
