"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from .common import (
    ExtensionType,
    StringWithNilReasonType,
)
from .met_feature import (
    ElevatedLevelPropertyType,
    MeteorologicalFeatureCollectionType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.gml_base import (
    AbstractGmltype,
    ReferenceType,
)
from .xlink import (
    ActuateType,
    ShowType,
    TypeType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2025-2"


class VolcanicAshCloudMovementType(Enum):
    """
    Volcanic ash cloud movement.

    Properties
    ----------
    UNKNOWN
        Unknown.
    OBSCURED
        Obscured.
    VERTICAL
        Vertical.
    NW
        Northwest.
    W
        West.
    SW
        Southwest.
    S
        South.
    SE
        Southeast.
    E
        East.
    NE
        Northeast.
    N
        North.
    """

    UNKNOWN = "UNKNOWN"
    OBSCURED = "OBSCURED"
    VERTICAL = "VERTICAL"
    NW = "NW"
    W = "W"
    SW = "SW"
    S = "S"
    SE = "SE"
    E = "E"
    NE = "NE"
    N = "N"


class AviationColourCodeType(ReferenceType):
    """
    Volcano level of alert colour codes for aviation.

    See ICAO Doc 9766 for details.
    """

    model_config = ConfigDict(defer_build=True)


class ResuspendedVolcanicAshType(AbstractGmltype):
    """
    Parameters
    ----------
    height
        Average height of re-suspended volcanic ash field. When the height is unknown, it shall be represented with a
        nil in name and nilReason 'http://codes.wmo.int/iwxxm/nil/unknown'.
    """

    model_config = ConfigDict(defer_build=True)
    height: None | ElevatedLevelPropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )


class VolcanicAshCloudVerticalExtentType(AbstractGmltype):
    """
    Parameters
    ----------
    height_source
        Source of height data (e.g. ground observer, air-report, radar, LIDAR, satellite, webcam, etc.).
    movement
        Direction of movement of the observed cloud.
    """

    model_config = ConfigDict(defer_build=True)
    height_source: None | StringWithNilReasonType = field(
        metadata={
            "name": "heightSource",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    movement: None | VolcanicAshCloudMovementType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )


class AviationColourCode(AviationColourCodeType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class ResuspendedVolcanicAsh(ResuspendedVolcanicAshType):
    """
    Re-suspended volcanic ash.

    To be used in iwxxm:phenomenonProperty of iwxxm:MeteorologicalFeature and iwxxm:phenomenon set to
    https://codes.wmo.int/iwxxm/MeteorologicalFeature/RESUSPENDED_VOLCANIC_ASH with iwxxm:phenomenonGeometry defined
    by iwxxm:ElevatedSurface to indicate the coverage of the re-suspended volcanic ash source.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class VolcanicAshCloudVerticalExtent(VolcanicAshCloudVerticalExtentType):
    """
    Volcanic ash cloud vertical extent.

    To be used in iwxxm:phenomenonProperty of iwxxm:MeteorologicalFeature and iwxxm:phenomenon set to
    https://codes.wmo.int/iwxxm/MeteorologicalFeature/VOLCANIC_ASH with iwxxm:phenomenonGeometry defined by
    iwxxm:ElevatedLevel to indicate the height of the volcanic ash cloud. When the cloud height is unknown, set
    iwxxm:phenomenon/../iwxxm:ElevatedLevel to nil with nilReason http://codes.wmo.int/iwxxm/nil/unknown. When no
    volcanic cloud is produced, set iwxxm:phenomenonGeometry, iwxxm:heightSource and iwxxm:movement to nil with
    nilReason http://codes.wmo.int/iwxxm/nil/inapplicable.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class VolcanoObservatoryNoticeForAviationType(MeteorologicalFeatureCollectionType):
    """
    Parameters
    ----------
    state_or_region
        State or region involved.
    notice_number
        VONA Notice Number.
    current_colour_code
        Current aviation colour code.
    previous_colour_code
        Previous aviation colour code.
    contacts
        State Volcano Observatory (SVO) contact details.
    remarks
        Remarks.
    next_notice
        Indication of the issuance of next VONA.
    extension
        Extension block for optional and/or additional parameters for element VolcanoObservatoryNoticeForAviation
    """

    model_config = ConfigDict(defer_build=True)
    state_or_region: StringWithNilReasonType = field(
        metadata={
            "name": "stateOrRegion",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    notice_number: StringWithNilReasonType = field(
        metadata={
            "name": "noticeNumber",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    current_colour_code: None | AviationColourCodeType = field(
        metadata={
            "name": "currentColourCode",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    previous_colour_code: None | AviationColourCodeType = field(
        metadata={
            "name": "previousColourCode",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    contacts: StringWithNilReasonType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    remarks: StringWithNilReasonType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    next_notice: StringWithNilReasonType = field(
        metadata={
            "name": "nextNotice",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class ResuspendedVolcanicAshPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    resuspended_volcanic_ash: None | ResuspendedVolcanicAsh = field(
        default=None,
        metadata={
            "name": "ResuspendedVolcanicAsh",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class VolcanicAshCloudVerticalExtentPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    volcanic_ash_cloud_vertical_extent: None | VolcanicAshCloudVerticalExtent = field(
        default=None,
        metadata={
            "name": "VolcanicAshCloudVerticalExtent",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class VolcanoObservatoryNoticeForAviation(VolcanoObservatoryNoticeForAviationType):
    """
    A product issued by the State Volcano Observatory (SVO) with a summary of volcanic activity and observations
    about ash emission (or lack thereof) which is intended for aviation users.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class VolcanoObservatoryNoticeForAviationPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    volcano_observatory_notice_for_aviation: (
        None | VolcanoObservatoryNoticeForAviation
    ) = field(
        default=None,
        metadata={
            "name": "VolcanoObservatoryNoticeForAviation",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
