"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from .common import (
    ExtensionType,
    StringWithNilReasonType,
    ValDistanceVerticalType,
    VelocityWithNilReasonType,
)
from .met_feature import (
    ElevatedPointPropertyType,
    MeteorologicalFeatureCollectionType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.basic_types import (
    NilReasonEnumerationValue,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.gml_base import (
    AbstractGmltype,
    ReferenceType,
)
from .schemas.opengis.net.gml.pkg_3.pkg_2.pkg_1.temporal import TimeInstantPropertyType
from .www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_data_types import (
    CodeVerticalReferenceBaseTypeValue,
)
from .xlink import (
    ActuateType,
    ShowType,
    TypeType,
)

__NAMESPACE__ = "http://icao.int/iwxxm/2025-2"


class WorldAreaForecastCentreType(Enum):
    """
    WorldAreaForecastCentre identifies the institution that creates the report.

    Properties
    ----------
    WASHINGTON
        The World Area Forecast Centre (WAFC) operated by the National Weather Service (NWS) in the USA.
    LONDON
        The World Area Forecast Centre (WAFC) operated by the UK Met Office.
    """

    WASHINGTON = "Washington"
    LONDON = "London"


class CloudDistributionType(ReferenceType):
    """
    Cloud distribution.

    See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 008 "Cloud Distribution for Aviation".
    """

    model_config = ConfigDict(defer_build=True)


class CloudTypeType(ReferenceType):
    """
    Cloud type.

    See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 012 "Cloud Type".
    """

    model_config = ConfigDict(defer_build=True)


class DegreeOfIcingType(ReferenceType):
    """
    Degree of icing.

    See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 041 "Airframe Icing".
    """

    model_config = ConfigDict(defer_build=True)


class DegreeOfTurbulenceType(ReferenceType):
    """
    Degree of turbulence.

    See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 11 030 "Extended Degree of Turbulence".
    """

    model_config = ConfigDict(defer_build=True)


class RadiationIncidentType(AbstractGmltype):
    """
    Parameters
    ----------
    site_name
        Incident location.
    incident_time
        Incident time.
    """

    model_config = ConfigDict(defer_build=True)
    site_name: None | StringWithNilReasonType = field(
        metadata={
            "name": "siteName",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    incident_time: TimeInstantPropertyType = field(
        metadata={
            "name": "incidentTime",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )


class WafsjetStreamWindSymbolType(AbstractGmltype):
    """
    Parameters
    ----------
    location
        Position of the wind symbol.
    wind_speed
        Horizontal wind speed at the indicated position. Wind speeds shall be provided in either two units of
        measure, "m/s" (meters per second) or "[kn_i]" (knot).
    isotach_upper_elevation
        The vertical distance of the 80 knot isotach above the jet stream measured from vertical reference.
    isotach_upper_vertical_reference
        A code indicating the reference for a vertical distance. Two series of values exist: 1) real distance: from
        GND, from the MSL, from the WGS-84 ellipsoid; 2) distance based on a difference of pressures, according to
        the standard atmosphere.
    isotach_lower_elevation
        The vertical distance of the 80 knot isotach below the jet stream measured from vertical reference.
    isotach_lower_vertical_reference
        A code indicating the reference for a vertical distance. Two series of values exist: 1) real distance: from
        GND, from the MSL, from the WGS-84 ellipsoid; 2) distance based on a difference of pressures, according to
        the standard atmosphere.
    """

    class Meta:
        name = "WAFSJetStreamWindSymbolType"

    model_config = ConfigDict(defer_build=True)
    location: ElevatedPointPropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        }
    )
    wind_speed: None | VelocityWithNilReasonType = field(
        metadata={
            "name": "windSpeed",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        }
    )
    isotach_upper_elevation: None | ValDistanceVerticalType = field(
        default=None,
        metadata={
            "name": "IsotachUpperElevation",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    isotach_upper_vertical_reference: (
        None | str | CodeVerticalReferenceBaseTypeValue
    ) = field(
        default=None,
        metadata={
            "name": "IsotachUpperVerticalReference",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "pattern": r"OTHER(:(\w|_){1,58})?",
        },
    )
    isotach_lower_elevation: None | ValDistanceVerticalType = field(
        default=None,
        metadata={
            "name": "IsotachLowerElevation",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "nillable": True,
        },
    )
    isotach_lower_vertical_reference: (
        None | str | CodeVerticalReferenceBaseTypeValue
    ) = field(
        default=None,
        metadata={
            "name": "IsotachLowerVerticalReference",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
            "pattern": r"OTHER(:(\w|_){1,58})?",
        },
    )


class WafssignificantWeatherForecastType(MeteorologicalFeatureCollectionType):
    """
    Parameters
    ----------
    extension
        Extension block for optional and/or additional parameters for element WAFSSignificantWeatherForecast
    """

    class Meta:
        name = "WAFSSignificantWeatherForecastType"

    model_config = ConfigDict(defer_build=True)
    extension: list[ExtensionType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )


class WorldAreaForecastCentre(BaseModel):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)
    value: WorldAreaForecastCentreType = field()


class CloudDistribution(CloudDistributionType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class CloudType(CloudTypeType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class DegreeOfIcing(DegreeOfIcingType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class DegreeOfTurbulence(DegreeOfTurbulenceType):
    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class RadiationIncident(RadiationIncidentType):
    """
    A radiation incident characterised by the location name and incident time.
    """

    class Meta:
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class WafsjetStreamWindSymbol(WafsjetStreamWindSymbolType):
    """
    Child element of iwxxm:phenomenonProperty when the parent iwxxm:MeteorologicalFeature is being used to represent
    a WAFS Jet Stream Wind Symbol.

    Describes the horizontal wind speed and direction at the point and optionally the elevation of the 80kt isotach
    below and above the maximum wind speed level if available.
    """

    class Meta:
        name = "WAFSJetStreamWindSymbol"
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class WafssignificantWeatherForecast(WafssignificantWeatherForecastType):
    """
    Forecasts of significant en-route weather phenomena provided by the World Area Forecast System (WAFS).

    See ICAO Annex 3 and PANS-MET (Doc 10157) for details.
    """

    class Meta:
        name = "WAFSSignificantWeatherForecast"
        namespace = "http://icao.int/iwxxm/2025-2"

    model_config = ConfigDict(defer_build=True)


class RadiationIncidentPropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    radiation_incident: None | RadiationIncident = field(
        default=None,
        metadata={
            "name": "RadiationIncident",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class WafsjetStreamWindSymbolPropertyType(BaseModel):
    class Meta:
        name = "WAFSJetStreamWindSymbolPropertyType"

    model_config = ConfigDict(defer_build=True)
    wafsjet_stream_wind_symbol: None | WafsjetStreamWindSymbol = field(
        default=None,
        metadata={
            "name": "WAFSJetStreamWindSymbol",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class WafssignificantWeatherForecastPropertyType(BaseModel):
    class Meta:
        name = "WAFSSignificantWeatherForecastPropertyType"

    model_config = ConfigDict(defer_build=True)
    wafssignificant_weather_forecast: None | WafssignificantWeatherForecast = field(
        default=None,
        metadata={
            "name": "WAFSSignificantWeatherForecast",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
