"""Environment variable names shared across backend and frontend."""

METAR_CORS_ORIGINS_ENV = "METAR_CORS_ORIGINS"
VITE_API_BASE_URL_ENV = "VITE_API_BASE_URL"
VITE_SUPABASE_URL_ENV = "VITE_SUPABASE_URL"
VITE_SUPABASE_PUBLISHABLE_KEY_ENV = "VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY"
VITE_APP_URL_ENV = "VITE_APP_URL"
