"""Join ISSUE_CATALOG codes to WMO/ICAO/IWXXM source attribution (EV-040 / F15).

Loads packaged ``catalog_attribution.json`` (generated by ``make catalog-regen`` from
``PROVENANCE_MAP.json``). Citations and URLs only — no copyrighted Annex prose.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, cast

_DATA = Path(__file__).resolve().parent / "data" / "catalog_attribution.json"


@lru_cache(maxsize=1)
def _load() -> dict[str, dict[str, Any]]:
    if not _DATA.is_file():
        return {}
    try:
        loaded: object = json.loads(_DATA.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(loaded, dict):
        return {}
    payload = cast(dict[str, object], loaded)
    codes_obj = payload.get("codes")
    if not isinstance(codes_obj, dict):
        return {}
    codes = cast(dict[object, object], codes_obj)
    out: dict[str, dict[str, Any]] = {}
    for key_obj, value_obj in codes.items():
        if not isinstance(value_obj, dict):
            continue
        out[str(key_obj)] = cast(dict[str, Any], value_obj)
    return out


def attribution_for(code: str) -> dict[str, str | None]:
    """
    Return source attribution fields for a registry code.

    Parameters
    ----------
    code :
        Stable SCREAMING_SNAKE issue code.

    Returns
    -------
    dict[str, str | None]
        Keys ``source_id``, ``source_url``, ``source_attribution`` (may be None).
    """
    row = _load().get(code) or {}
    source_id_obj: object = row.get("source_id")
    source_url_obj: object = row.get("source_url")
    status_obj: object = row.get("status")
    note_obj: object = row.get("note")
    source_id = source_id_obj if isinstance(source_id_obj, str) else None
    source_url = source_url_obj if isinstance(source_url_obj, str) else None
    status = status_obj if isinstance(status_obj, str) else None
    note = note_obj if isinstance(note_obj, str) else None
    parts: list[str] = []
    if source_id:
        parts.append(source_id)
    if status in {"paywall", "gap", "N/A"}:
        parts.append(f"access:{status}")
    if note:
        parts.append(note)
    elif source_url:
        parts.append(source_url)
    attribution = " — ".join(parts) if parts else None
    return {
        "source_id": source_id,
        "source_url": source_url,
        "source_attribution": attribution,
    }


__all__ = ["attribution_for"]
