"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict
from xsdata.models.datatype import XmlDate, XmlDateTime
from xsdata_pydantic.fields import field

from ........xlink import (
    ActuateType,
    ShowType,
    TypeType,
)
from .basic_types import (
    CodeType,
    CodeWithAuthorityType,
    MeasureType,
    NilReasonEnumerationValue,
)
from .deprecated_types import (
    AnchorPoint,
    UsesEllipsoid,
    UsesPrimeMeridian,
)
from .measures import (
    AngleType,
    LengthType,
)
from .reference_systems import (
    DomainOfValidity,
    IdentifiedObjectType,
    Scope,
)

__NAMESPACE__ = "http://www.opengis.net/gml/3.2"


class Origin(BaseModel):
    """
    gml:origin is the date and time origin of this temporal datum.
    """

    class Meta:
        name = "origin"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
    value: XmlDateTime = field()


class RealizationEpoch(BaseModel):
    """
    gml:realizationEpoch is the time after which this datum definition is valid.

    See ISO 19111 Table 32 for details.
    """

    class Meta:
        name = "realizationEpoch"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
    value: XmlDate = field()


class SecondDefiningParameter1(BaseModel):
    class Meta:
        name = "SecondDefiningParameter"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
    inverse_flattening: None | MeasureType = field(
        default=None,
        metadata={
            "name": "inverseFlattening",
            "type": "Element",
        },
    )
    semi_minor_axis: None | LengthType = field(
        default=None,
        metadata={
            "name": "semiMinorAxis",
            "type": "Element",
        },
    )
    is_sphere: None | bool = field(
        default=None,
        metadata={
            "name": "isSphere",
            "type": "Element",
        },
    )


class AnchorDefinition(CodeType):
    """
    gml:anchorDefinition is a description, possibly including coordinates, of the definition used to anchor the
    datum to the Earth.

    Also known as the "origin", especially for engineering and image datums. The codeSpace attribute may be used to
    reference a source of more detailed on this point or surface, or on a set of such descriptions. - For a geodetic
    datum, this point is also known as the fundamental point, which is traditionally the point where the
    relationship between geoid and ellipsoid is defined. In some cases, the "fundamental point" may consist of a
    number of points. In those cases, the parameters defining the geoid/ellipsoid relationship have been averaged
    for these points, and the averages adopted as the datum definition. - For an engineering datum, the anchor
    definition may be a physical point, or it may be a point with defined coordinates in another CRS.may - For an
    image datum, the anchor definition is usually either the centre of the image or the corner of the image. - For a
    temporal datum, this attribute is not defined. Instead of the anchor definition, a temporal datum carries a
    separate time origin of type DateTime.
    """

    class Meta:
        name = "anchorDefinition"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class GreenwichLongitude(AngleType):
    """
    gml:greenwichLongitude is the longitude of the prime meridian measured from the Greenwich meridian, positive
    eastward.

    If the value of the prime meridian "name" is "Greenwich" then the value of greenwichLongitude shall be 0
    degrees.
    """

    class Meta:
        name = "greenwichLongitude"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class PixelInCell(CodeWithAuthorityType):
    """
    gml:pixelInCell is a specification of the way an image grid is associated with the image data attributes.

    The required codeSpace attribute shall reference a source of information specifying the values and meanings of
    all the allowed string values for this property.
    """

    class Meta:
        name = "pixelInCell"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class SemiMajorAxis(MeasureType):
    """
    gml:semiMajorAxis specifies the length of the semi-major axis of the ellipsoid, with its units.

    Uses the MeasureType with the restriction that the unit of measure referenced by uom must be suitable for a
    length, such as metres or feet.
    """

    class Meta:
        name = "semiMajorAxis"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class AbstractDatumType(IdentifiedObjectType):
    model_config = ConfigDict(defer_build=True)
    domain_of_validity: None | DomainOfValidity = field(
        default=None,
        metadata={
            "name": "domainOfValidity",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    scope: list[Scope] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
            "min_occurs": 1,
        },
    )
    anchor_point: None | AnchorPoint = field(
        default=None,
        metadata={
            "name": "anchorPoint",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    anchor_definition: None | AnchorDefinition = field(
        default=None,
        metadata={
            "name": "anchorDefinition",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    realization_epoch: None | RealizationEpoch = field(
        default=None,
        metadata={
            "name": "realizationEpoch",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class PrimeMeridianType(IdentifiedObjectType):
    model_config = ConfigDict(defer_build=True)
    greenwich_longitude: GreenwichLongitude = field(
        metadata={
            "name": "greenwichLongitude",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )


class SecondDefiningParameter2(BaseModel):
    """
    gml:secondDefiningParameter is a property containing the definition of the second parameter that defines the
    shape of an ellipsoid.

    An ellipsoid requires two defining parameters: semi-major axis and inverse flattening or semi-major axis and
    semi-minor axis. When the reference body is a sphere rather than an ellipsoid, only a single defining parameter
    is required, namely the radius of the sphere; in that case, the semi-major axis "degenerates" into the radius of
    the sphere. The inverseFlattening element contains the inverse flattening value of the ellipsoid. This value is
    a scale factor (or ratio). It uses gml:LengthType with the restriction that the unit of measure referenced by
    the uom attribute must be suitable for a scale factor, such as percent, permil, or parts-per-million. The
    semiMinorAxis element contains the length of the semi-minor axis of the ellipsoid. When the isSphere element is
    included, the ellipsoid is degenerate and is actually a sphere. The sphere is completely defined by the
    semi-major axis, which is the radius of the sphere.
    """

    class Meta:
        name = "secondDefiningParameter"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
    second_defining_parameter: SecondDefiningParameter1 = field(
        metadata={
            "name": "SecondDefiningParameter",
            "type": "Element",
        }
    )


class AbstractDatum(AbstractDatumType):
    """
    A gml:AbstractDatum specifies the relationship of a coordinate system to the earth, thus creating a coordinate
    reference system.

    A datum uses a parameter or set of parameters that determine the location of the origin of the coordinate
    reference system. Each datum subtype may be associated with only specific types of coordinate systems. This
    abstract complex type shall not be used, extended, or restricted, in a GML Application Schema, to define a
    concrete subtype with a meaning equivalent to a concrete subtype specified in this document.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class EllipsoidType(IdentifiedObjectType):
    model_config = ConfigDict(defer_build=True)
    semi_major_axis: SemiMajorAxis = field(
        metadata={
            "name": "semiMajorAxis",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )
    second_defining_parameter: SecondDefiningParameter2 = field(
        metadata={
            "name": "secondDefiningParameter",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )


class EngineeringDatumType(AbstractDatumType):
    pass
    model_config = ConfigDict(defer_build=True)


class ImageDatumType(AbstractDatumType):
    model_config = ConfigDict(defer_build=True)
    pixel_in_cell: PixelInCell = field(
        metadata={
            "name": "pixelInCell",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )


class PrimeMeridian1(PrimeMeridianType):
    """
    A gml:PrimeMeridian defines the origin from which longitude values are determined.

    The default value for the prime meridian gml:identifier value is "Greenwich".
    """

    class Meta:
        name = "PrimeMeridian"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TemporalDatumBaseType(AbstractDatumType):
    """
    The TemporalDatumBaseType partially defines the origin of a temporal coordinate reference system.

    This type restricts the AbstractDatumType to remove the "anchorDefinition" and "realizationEpoch" elements.
    """

    model_config = ConfigDict(defer_build=True)
    anchor_point: Any = field(
        exclude=True,
        default=None,
        metadata={
            "type": "Ignore",
        },
    )
    anchor_definition: Any = field(
        exclude=True,
        default=None,
        metadata={
            "type": "Ignore",
        },
    )
    realization_epoch: Any = field(
        exclude=True,
        default=None,
        metadata={
            "type": "Ignore",
        },
    )


class VerticalDatumType(AbstractDatumType):
    pass
    model_config = ConfigDict(defer_build=True)


class Ellipsoid1(EllipsoidType):
    """
    A gml:Ellipsoid is a geometric figure that may be used to describe the approximate shape of the earth.

    In mathematical terms, it is a surface formed by the rotation of an ellipse about its minor axis.
    """

    class Meta:
        name = "Ellipsoid"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class EngineeringDatum1(EngineeringDatumType):
    """
    gml:EngineeringDatum defines the origin of an engineering coordinate reference system, and is used in a region
    around that origin.

    This origin may be fixed with respect to the earth (such as a defined point at a construction site), or be a
    defined point on a moving vehicle (such as on a ship or satellite).
    """

    class Meta:
        name = "EngineeringDatum"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class ImageDatum1(ImageDatumType):
    """
    gml:ImageDatum defines the origin of an image coordinate reference system, and is used in a local context only.

    For an image datum, the anchor definition is usually either the centre of the image or the corner of the image.
    For more information, see ISO 19111 B.3.5.
    """

    class Meta:
        name = "ImageDatum"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class PrimeMeridianPropertyType(BaseModel):
    """
    gml:PrimeMeridianPropertyType is a property type for association roles to a prime meridian, either referencing
    or containing the definition of that meridian.
    """

    model_config = ConfigDict(defer_build=True)
    prime_meridian: None | PrimeMeridian1 = field(
        default=None,
        metadata={
            "name": "PrimeMeridian",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class TemporalDatumType(TemporalDatumBaseType):
    model_config = ConfigDict(defer_build=True)
    origin: Origin = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )


class VerticalDatum1(VerticalDatumType):
    """
    gml:VerticalDatum is a textual description and/or a set of parameters identifying a particular reference level
    surface used as a zero-height surface, including its position with respect to the Earth for any of the height
    types recognized by this International Standard.
    """

    class Meta:
        name = "VerticalDatum"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class EllipsoidPropertyType(BaseModel):
    """
    gml:EllipsoidPropertyType is a property type for association roles to an ellipsoid, either referencing or
    containing the definition of that ellipsoid.
    """

    model_config = ConfigDict(defer_build=True)
    ellipsoid: None | Ellipsoid1 = field(
        default=None,
        metadata={
            "name": "Ellipsoid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class EngineeringDatumPropertyType(BaseModel):
    """
    gml:EngineeringDatumPropertyType is a property type for association roles to an engineering datum, either
    referencing or containing the definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    engineering_datum: None | EngineeringDatum1 = field(
        default=None,
        metadata={
            "name": "EngineeringDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class ImageDatumPropertyType(BaseModel):
    """
    gml:ImageDatumPropertyType is a property type for association roles to an image datum, either referencing or
    containing the definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    image_datum: None | ImageDatum1 = field(
        default=None,
        metadata={
            "name": "ImageDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class TemporalDatum1(TemporalDatumType):
    """
    A gml:TemporalDatum defines the origin of a Temporal Reference System.

    This type omits the "anchorDefinition" and "realizationEpoch" elements and adds the "origin" element with the
    dateTime type.
    """

    class Meta:
        name = "TemporalDatum"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class VerticalDatumPropertyType(BaseModel):
    """
    gml:VerticalDatumPropertyType is property type for association roles to a vertical datum, either referencing or
    containing the definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    vertical_datum: None | VerticalDatum1 = field(
        default=None,
        metadata={
            "name": "VerticalDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class PrimeMeridian2(PrimeMeridianPropertyType):
    """
    gml:primeMeridian is an association role to the prime meridian used by this geodetic datum.
    """

    class Meta:
        name = "primeMeridian"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class TemporalDatumPropertyType(BaseModel):
    """
    gml:TemporalDatumPropertyType is a property type for association roles to a temporal datum, either referencing
    or containing the definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    temporal_datum: None | TemporalDatum1 = field(
        default=None,
        metadata={
            "name": "TemporalDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class Ellipsoid2(EllipsoidPropertyType):
    """
    gml:ellipsoid is an association role to the ellipsoid used by this geodetic datum.
    """

    class Meta:
        name = "ellipsoid"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class GeodeticDatumType(AbstractDatumType):
    model_config = ConfigDict(defer_build=True)
    uses_prime_meridian: None | UsesPrimeMeridian = field(
        default=None,
        metadata={
            "name": "usesPrimeMeridian",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    prime_meridian: None | PrimeMeridian2 = field(
        default=None,
        metadata={
            "name": "primeMeridian",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    uses_ellipsoid: None | UsesEllipsoid = field(
        default=None,
        metadata={
            "name": "usesEllipsoid",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    ellipsoid: None | Ellipsoid2 = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class GeodeticDatum1(GeodeticDatumType):
    """
    gml:GeodeticDatum is a geodetic datum defines the precise location and orientation in 3-dimensional space of a
    defined ellipsoid (or sphere), or of a Cartesian coordinate system centered in this ellipsoid (or sphere).
    """

    class Meta:
        name = "GeodeticDatum"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class DatumPropertyType(BaseModel):
    """
    gml:DatumPropertyType is a property type for association roles to a datum, either referencing or containing the
    definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    temporal_datum: None | TemporalDatum1 = field(
        default=None,
        metadata={
            "name": "TemporalDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    vertical_datum: None | VerticalDatum1 = field(
        default=None,
        metadata={
            "name": "VerticalDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    image_datum: None | ImageDatum1 = field(
        default=None,
        metadata={
            "name": "ImageDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    engineering_datum: None | EngineeringDatum1 = field(
        default=None,
        metadata={
            "name": "EngineeringDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    geodetic_datum: None | GeodeticDatum1 = field(
        default=None,
        metadata={
            "name": "GeodeticDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class GeodeticDatumPropertyType(BaseModel):
    """
    gml:GeodeticDatumPropertyType is a property type for association roles to a geodetic datum, either referencing
    or containing the definition of that datum.
    """

    model_config = ConfigDict(defer_build=True)
    geodetic_datum: None | GeodeticDatum1 = field(
        default=None,
        metadata={
            "name": "GeodeticDatum",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
