"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from ........airmet import (
    Airmet,
    AirmetevolvingCondition,
    AirmetevolvingConditionCollection,
)
from ........met_feature import (
    ElevatedEnvelope,
    MeteorologicalFeature,
    MeteorologicalFeatureCollection,
)
from ........metar_speci import (
    Metar,
    Speci,
)
from ........qvaci import QuantitativeVolcanicAshConcentrationInformation
from ........sigmet import (
    AnalysisAndForecastPositionAnalysis,
    Sigmet,
    SigmetevolvingCondition,
    SigmetevolvingConditionCollection,
    Sigmetposition,
    SigmetpositionCollection,
    TropicalCycloneSigmet,
    VolcanicAshSigmet,
)
from ........space_wx_advisory import (
    SpaceWeatherAdvisory,
    SpaceWeatherAnalysis,
)
from ........taf import Taf
from ........tropical_cyclone_advisory import (
    TropicalCycloneAdvisory,
    TropicalCycloneForecastConditions,
    TropicalCycloneObservedConditions,
)
from ........volcanic_ash_advisory import (
    VolcanicAshAdvisory,
    VolcanicAshCloudForecast,
    VolcanicAshCloudObservedOrEstimated,
    VolcanicAshForecastConditions,
    VolcanicAshObservedOrEstimatedConditions,
    WindObservedOrEstimated,
)
from ........vona import VolcanoObservatoryNoticeForAviation
from ........wafssig_wx_fc import WafssignificantWeatherForecast
from ........www.aixm.aero.schema.pkg_5.pkg_1.pkg_1.aixm_features import (
    AerialRefuelling,
    AeronauticalGroundLight,
    AircraftGroundService,
    AircraftStand,
    AirportClearanceService,
    AirportHeliport,
    AirportHeliportCollocation,
    AirportHotSpot,
    AirportProtectionAreaMarking,
    AirportSuppliesService,
    Airspace,
    AirspaceBorderCrossing,
    AirTrafficControlService,
    AirTrafficManagementService,
    AltimeterSource,
    AngleIndication,
    ApproachLightingSystem,
    Apron,
    ApronElement,
    ApronLightSystem,
    ApronMarking,
    ArrestingGear,
    ArrivalFeederLeg,
    ArrivalLeg,
    AuthorityForAirspace,
    Azimuth,
    ChangeOverPoint,
    CheckpointIns,
    CheckpointVor,
    CirclingArea,
    DeicingArea,
    DeicingAreaMarking,
    DepartureLeg,
    DesignatedPoint,
    DirectionFinder,
    DistanceIndication,
    Dme,
    Elevation,
    FinalLeg,
    FireFightingService,
    FlightRestriction,
    FloatingDockSite,
    GeoBorder,
    Glidepath,
    GroundTrafficControlService,
    GuidanceLine,
    GuidanceLineLightSystem,
    GuidanceLineMarking,
    HoldingAssessment,
    HoldingPattern,
    InformationService,
    InitialLeg,
    InstrumentApproachProcedure,
    IntermediateLeg,
    Localizer,
    MarkerBeacon,
    MarkingBuoy,
    MissedApproachLeg,
    Navaid,
    NavigationArea,
    NavigationAreaRestriction,
    Ndb,
    NonMovementArea,
    ObstacleArea,
    OrganisationAuthority,
    PassengerLoadingBridge,
    PassengerService,
    PilotControlledLighting,
    PrecisionApproachRadar,
    PrimarySurveillanceRadar,
    ProcedureDme,
    RadarSystem,
    RadioCommunicationChannel,
    RadioFrequencyArea,
    Road,
    Route,
    RouteDme,
    RouteSegment,
    RulesProcedures,
    Runway,
    RunwayBlastPad,
    RunwayCentrelinePoint,
    RunwayDirection,
    RunwayDirectionLightSystem,
    RunwayElement,
    RunwayMarking,
    RunwayProtectArea,
    RunwayProtectAreaLightSystem,
    RunwayVisualRange,
    SafeAltitudeArea,
    Sdf,
    SeaplaneLandingArea,
    SeaplaneRampSite,
    SearchRescueService,
    SecondarySurveillanceRadar,
    SignificantPointInAirspace,
    SpecialDate,
    SpecialNavigationStation,
    SpecialNavigationSystem,
    StandardInstrumentArrival,
    StandardInstrumentDeparture,
    StandardLevelColumn,
    StandardLevelSector,
    StandardLevelTable,
    StandMarking,
    SurveyControlPoint,
    Tacan,
    TaxiHoldingPosition,
    TaxiHoldingPositionLightSystem,
    TaxiHoldingPositionMarking,
    Taxiway,
    TaxiwayElement,
    TaxiwayLightSystem,
    TaxiwayMarking,
    TerminalArrivalArea,
    TouchDownLiftOff,
    TouchDownLiftOffLightSystem,
    TouchDownLiftOffMarking,
    TouchDownLiftOffSafeArea,
    Unit,
    UnplannedHolding,
    VerticalStructure,
    VisualGlideSlopeIndicator,
    Vor,
    WorkArea,
)
from ........xlink import (
    ActuateType,
    ShowType,
    TypeType,
)
from .......wmo.int_pkg.metce.pkg_1.pkg_2.phenomena import (
    EruptingVolcano,
    TropicalCyclone,
    Volcano,
)
from .......wmo.int_pkg.metce.pkg_1.pkg_2.procedure import Process
from .basic_types import (
    CodeType,
    NilReasonEnumerationValue,
)
from .coverage import (
    GridCoverage,
    MultiCurveCoverage,
    MultiPointCoverage,
    MultiSolidCoverage,
    MultiSurfaceCoverage,
    RectifiedGridCoverage,
)
from .deprecated_types import (
    Location,
    Null,
    PriorityLocation,
)
from .dynamic_feature import (
    DynamicFeature,
    DynamicFeatureCollection,
)
from .geometry_basic0d1d import (
    Envelope,
    EnvelopeType,
)
from .gml_base import (
    AbstractGmltype,
    ReferenceType,
)
from .temporal import TimePositionType

__NAMESPACE__ = "http://www.opengis.net/gml/3.2"


class AbstractFeatureMemberType(BaseModel):
    """
    To create a collection of GML features, a property type shall be derived by extension from
    gml:AbstractFeatureMemberType.

    By default, this abstract property type does not imply any ownership of the features in the collection. The owns
    attribute of gml:OwnershipAttributeGroup may be used on a property element instance to assert ownership of a
    feature in the collection. A collection shall not own a feature already owned by another object.
    """

    model_config = ConfigDict(defer_build=True)
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )


class EnvelopeWithTimePeriodType(EnvelopeType):
    model_config = ConfigDict(defer_build=True)
    begin_position: TimePositionType = field(
        metadata={
            "name": "beginPosition",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )
    end_position: TimePositionType = field(
        metadata={
            "name": "endPosition",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        }
    )
    frame: str = field(
        default="#ISO-8601",
        metadata={
            "type": "Attribute",
        },
    )


class FeaturePropertyType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    sigmetposition: None | Sigmetposition = field(
        default=None,
        metadata={
            "name": "SIGMETPosition",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    sigmetposition_collection: None | SigmetpositionCollection = field(
        default=None,
        metadata={
            "name": "SIGMETPositionCollection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    sigmetevolving_condition: None | SigmetevolvingCondition = field(
        default=None,
        metadata={
            "name": "SIGMETEvolvingCondition",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    sigmetevolving_condition_collection: None | SigmetevolvingConditionCollection = (
        field(
            default=None,
            metadata={
                "name": "SIGMETEvolvingConditionCollection",
                "type": "Element",
                "namespace": "http://icao.int/iwxxm/2025-2",
            },
        )
    )
    analysis_and_forecast_position_analysis: (
        None | AnalysisAndForecastPositionAnalysis
    ) = field(
        default=None,
        metadata={
            "name": "analysisAndForecastPositionAnalysis",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    airmetevolving_condition: None | AirmetevolvingCondition = field(
        default=None,
        metadata={
            "name": "AIRMETEvolvingCondition",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    airmetevolving_condition_collection: None | AirmetevolvingConditionCollection = (
        field(
            default=None,
            metadata={
                "name": "AIRMETEvolvingConditionCollection",
                "type": "Element",
                "namespace": "http://icao.int/iwxxm/2025-2",
            },
        )
    )
    tropical_cyclone_forecast_conditions: None | TropicalCycloneForecastConditions = (
        field(
            default=None,
            metadata={
                "name": "TropicalCycloneForecastConditions",
                "type": "Element",
                "namespace": "http://icao.int/iwxxm/2025-2",
            },
        )
    )
    tropical_cyclone_observed_conditions: None | TropicalCycloneObservedConditions = (
        field(
            default=None,
            metadata={
                "name": "TropicalCycloneObservedConditions",
                "type": "Element",
                "namespace": "http://icao.int/iwxxm/2025-2",
            },
        )
    )
    volcanic_ash_cloud_forecast: None | VolcanicAshCloudForecast = field(
        default=None,
        metadata={
            "name": "VolcanicAshCloudForecast",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    wind_observed_or_estimated: None | WindObservedOrEstimated = field(
        default=None,
        metadata={
            "name": "WindObservedOrEstimated",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcanic_ash_cloud_observed_or_estimated: (
        None | VolcanicAshCloudObservedOrEstimated
    ) = field(
        default=None,
        metadata={
            "name": "VolcanicAshCloudObservedOrEstimated",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcanic_ash_forecast_conditions: None | VolcanicAshForecastConditions = field(
        default=None,
        metadata={
            "name": "VolcanicAshForecastConditions",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcanic_ash_observed_or_estimated_conditions: (
        None | VolcanicAshObservedOrEstimatedConditions
    ) = field(
        default=None,
        metadata={
            "name": "VolcanicAshObservedOrEstimatedConditions",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    erupting_volcano: None | EruptingVolcano = field(
        default=None,
        metadata={
            "name": "EruptingVolcano",
            "type": "Element",
            "namespace": "http://def.wmo.int/metce/2013",
        },
    )
    volcano: None | Volcano = field(
        default=None,
        metadata={
            "name": "Volcano",
            "type": "Element",
            "namespace": "http://def.wmo.int/metce/2013",
        },
    )
    tropical_cyclone: None | TropicalCyclone = field(
        default=None,
        metadata={
            "name": "TropicalCyclone",
            "type": "Element",
            "namespace": "http://def.wmo.int/metce/2013",
        },
    )
    process: None | Process = field(
        default=None,
        metadata={
            "name": "Process",
            "type": "Element",
            "namespace": "http://def.wmo.int/metce/2013",
        },
    )
    om_observation: None | OmObservation = field(
        default=None,
        metadata={
            "name": "OM_Observation",
            "type": "Element",
            "namespace": "http://www.opengis.net/om/2.0",
        },
    )
    space_weather_analysis: None | SpaceWeatherAnalysis = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAnalysis",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    meteorological_feature: None | MeteorologicalFeature = field(
        default=None,
        metadata={
            "name": "MeteorologicalFeature",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    wafssignificant_weather_forecast: None | WafssignificantWeatherForecast = field(
        default=None,
        metadata={
            "name": "WAFSSignificantWeatherForecast",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    quantitative_volcanic_ash_concentration_information: (
        None | QuantitativeVolcanicAshConcentrationInformation
    ) = field(
        default=None,
        metadata={
            "name": "QuantitativeVolcanicAshConcentrationInformation",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcano_observatory_notice_for_aviation: (
        None | VolcanoObservatoryNoticeForAviation
    ) = field(
        default=None,
        metadata={
            "name": "VolcanoObservatoryNoticeForAviation",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    meteorological_feature_collection: None | MeteorologicalFeatureCollection = field(
        default=None,
        metadata={
            "name": "MeteorologicalFeatureCollection",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    metar: None | Metar = field(
        default=None,
        metadata={
            "name": "METAR",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    speci: None | Speci = field(
        default=None,
        metadata={
            "name": "SPECI",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    taf: None | Taf = field(
        default=None,
        metadata={
            "name": "TAF",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcanic_ash_sigmet: None | VolcanicAshSigmet = field(
        default=None,
        metadata={
            "name": "VolcanicAshSIGMET",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    tropical_cyclone_sigmet: None | TropicalCycloneSigmet = field(
        default=None,
        metadata={
            "name": "TropicalCycloneSIGMET",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    sigmet: None | Sigmet = field(
        default=None,
        metadata={
            "name": "SIGMET",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    airmet: None | Airmet = field(
        default=None,
        metadata={
            "name": "AIRMET",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    tropical_cyclone_advisory: None | TropicalCycloneAdvisory = field(
        default=None,
        metadata={
            "name": "TropicalCycloneAdvisory",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    volcanic_ash_advisory: None | VolcanicAshAdvisory = field(
        default=None,
        metadata={
            "name": "VolcanicAshAdvisory",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    space_weather_advisory: None | SpaceWeatherAdvisory = field(
        default=None,
        metadata={
            "name": "SpaceWeatherAdvisory",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    radar_system: None | RadarSystem = field(
        default=None,
        metadata={
            "name": "RadarSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    secondary_surveillance_radar: None | SecondarySurveillanceRadar = field(
        default=None,
        metadata={
            "name": "SecondarySurveillanceRadar",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    primary_surveillance_radar: None | PrimarySurveillanceRadar = field(
        default=None,
        metadata={
            "name": "PrimarySurveillanceRadar",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    precision_approach_radar: None | PrecisionApproachRadar = field(
        default=None,
        metadata={
            "name": "PrecisionApproachRadar",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    holding_assessment: None | HoldingAssessment = field(
        default=None,
        metadata={
            "name": "HoldingAssessment",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    standard_level_table: None | StandardLevelTable = field(
        default=None,
        metadata={
            "name": "StandardLevelTable",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    standard_level_sector: None | StandardLevelSector = field(
        default=None,
        metadata={
            "name": "StandardLevelSector",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    standard_level_column: None | StandardLevelColumn = field(
        default=None,
        metadata={
            "name": "StandardLevelColumn",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    special_date: None | SpecialDate = field(
        default=None,
        metadata={
            "name": "SpecialDate",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    radio_frequency_area: None | RadioFrequencyArea = field(
        default=None,
        metadata={
            "name": "RadioFrequencyArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    ground_traffic_control_service: None | GroundTrafficControlService = field(
        default=None,
        metadata={
            "name": "GroundTrafficControlService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    air_traffic_control_service: None | AirTrafficControlService = field(
        default=None,
        metadata={
            "name": "AirTrafficControlService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    search_rescue_service: None | SearchRescueService = field(
        default=None,
        metadata={
            "name": "SearchRescueService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    information_service: None | InformationService = field(
        default=None,
        metadata={
            "name": "InformationService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    air_traffic_management_service: None | AirTrafficManagementService = field(
        default=None,
        metadata={
            "name": "AirTrafficManagementService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    passenger_service: None | PassengerService = field(
        default=None,
        metadata={
            "name": "PassengerService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    fire_fighting_service: None | FireFightingService = field(
        default=None,
        metadata={
            "name": "FireFightingService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_supplies_service: None | AirportSuppliesService = field(
        default=None,
        metadata={
            "name": "AirportSuppliesService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_clearance_service: None | AirportClearanceService = field(
        default=None,
        metadata={
            "name": "AirportClearanceService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    aircraft_ground_service: None | AircraftGroundService = field(
        default=None,
        metadata={
            "name": "AircraftGroundService",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    radio_communication_channel: None | RadioCommunicationChannel = field(
        default=None,
        metadata={
            "name": "RadioCommunicationChannel",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    pilot_controlled_lighting: None | PilotControlledLighting = field(
        default=None,
        metadata={
            "name": "PilotControlledLighting",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    rules_procedures: None | RulesProcedures = field(
        default=None,
        metadata={
            "name": "RulesProcedures",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    flight_restriction: None | FlightRestriction = field(
        default=None,
        metadata={
            "name": "FlightRestriction",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airspace_border_crossing: None | AirspaceBorderCrossing = field(
        default=None,
        metadata={
            "name": "AirspaceBorderCrossing",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    route_segment: None | RouteSegment = field(
        default=None,
        metadata={
            "name": "RouteSegment",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    route_dme: None | RouteDme = field(
        default=None,
        metadata={
            "name": "RouteDME",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    route: None | Route = field(
        default=None,
        metadata={
            "name": "Route",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    change_over_point: None | ChangeOverPoint = field(
        default=None,
        metadata={
            "name": "ChangeOverPoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    departure_leg: None | DepartureLeg = field(
        default=None,
        metadata={
            "name": "DepartureLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    arrival_leg: None | ArrivalLeg = field(
        default=None,
        metadata={
            "name": "ArrivalLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    missed_approach_leg: None | MissedApproachLeg = field(
        default=None,
        metadata={
            "name": "MissedApproachLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    intermediate_leg: None | IntermediateLeg = field(
        default=None,
        metadata={
            "name": "IntermediateLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    initial_leg: None | InitialLeg = field(
        default=None,
        metadata={
            "name": "InitialLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    final_leg: None | FinalLeg = field(
        default=None,
        metadata={
            "name": "FinalLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    arrival_feeder_leg: None | ArrivalFeederLeg = field(
        default=None,
        metadata={
            "name": "ArrivalFeederLeg",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    procedure_dme: None | ProcedureDme = field(
        default=None,
        metadata={
            "name": "ProcedureDME",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    standard_instrument_departure: None | StandardInstrumentDeparture = field(
        default=None,
        metadata={
            "name": "StandardInstrumentDeparture",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    standard_instrument_arrival: None | StandardInstrumentArrival = field(
        default=None,
        metadata={
            "name": "StandardInstrumentArrival",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    instrument_approach_procedure: None | InstrumentApproachProcedure = field(
        default=None,
        metadata={
            "name": "InstrumentApproachProcedure",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    navigation_area_restriction: None | NavigationAreaRestriction = field(
        default=None,
        metadata={
            "name": "NavigationAreaRestriction",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    safe_altitude_area: None | SafeAltitudeArea = field(
        default=None,
        metadata={
            "name": "SafeAltitudeArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    navigation_area: None | NavigationArea = field(
        default=None,
        metadata={
            "name": "NavigationArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    circling_area: None | CirclingArea = field(
        default=None,
        metadata={
            "name": "CirclingArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    terminal_arrival_area: None | TerminalArrivalArea = field(
        default=None,
        metadata={
            "name": "TerminalArrivalArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    unit: None | Unit = field(
        default=None,
        metadata={
            "name": "Unit",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    organisation_authority: None | OrganisationAuthority = field(
        default=None,
        metadata={
            "name": "OrganisationAuthority",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    vertical_structure: None | VerticalStructure = field(
        default=None,
        metadata={
            "name": "VerticalStructure",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    obstacle_area: None | ObstacleArea = field(
        default=None,
        metadata={
            "name": "ObstacleArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    aeronautical_ground_light: None | AeronauticalGroundLight = field(
        default=None,
        metadata={
            "name": "AeronauticalGroundLight",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    significant_point_in_airspace: None | SignificantPointInAirspace = field(
        default=None,
        metadata={
            "name": "SignificantPointInAirspace",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    designated_point: None | DesignatedPoint = field(
        default=None,
        metadata={
            "name": "DesignatedPoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    distance_indication: None | DistanceIndication = field(
        default=None,
        metadata={
            "name": "DistanceIndication",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    angle_indication: None | AngleIndication = field(
        default=None,
        metadata={
            "name": "AngleIndication",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    special_navigation_system: None | SpecialNavigationSystem = field(
        default=None,
        metadata={
            "name": "SpecialNavigationSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    special_navigation_station: None | SpecialNavigationStation = field(
        default=None,
        metadata={
            "name": "SpecialNavigationStation",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    checkpoint_vor: None | CheckpointVor = field(
        default=None,
        metadata={
            "name": "CheckpointVOR",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    checkpoint_ins: None | CheckpointIns = field(
        default=None,
        metadata={
            "name": "CheckpointINS",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    vor: None | Vor = field(
        default=None,
        metadata={
            "name": "VOR",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    tacan: None | Tacan = field(
        default=None,
        metadata={
            "name": "TACAN",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    sdf: None | Sdf = field(
        default=None,
        metadata={
            "name": "SDF",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    ndb: None | Ndb = field(
        default=None,
        metadata={
            "name": "NDB",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    marker_beacon: None | MarkerBeacon = field(
        default=None,
        metadata={
            "name": "MarkerBeacon",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    localizer: None | Localizer = field(
        default=None,
        metadata={
            "name": "Localizer",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    glidepath: None | Glidepath = field(
        default=None,
        metadata={
            "name": "Glidepath",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    elevation: None | Elevation = field(
        default=None,
        metadata={
            "name": "Elevation",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    dme: None | Dme = field(
        default=None,
        metadata={
            "name": "DME",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    direction_finder: None | DirectionFinder = field(
        default=None,
        metadata={
            "name": "DirectionFinder",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    azimuth: None | Azimuth = field(
        default=None,
        metadata={
            "name": "Azimuth",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    navaid: None | Navaid = field(
        default=None,
        metadata={
            "name": "Navaid",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    unplanned_holding: None | UnplannedHolding = field(
        default=None,
        metadata={
            "name": "UnplannedHolding",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    holding_pattern: None | HoldingPattern = field(
        default=None,
        metadata={
            "name": "HoldingPattern",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    geo_border: None | GeoBorder = field(
        default=None,
        metadata={
            "name": "GeoBorder",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    authority_for_airspace: None | AuthorityForAirspace = field(
        default=None,
        metadata={
            "name": "AuthorityForAirspace",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airspace: None | Airspace = field(
        default=None,
        metadata={
            "name": "Airspace",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxiway_element: None | TaxiwayElement = field(
        default=None,
        metadata={
            "name": "TaxiwayElement",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxiway: None | Taxiway = field(
        default=None,
        metadata={
            "name": "Taxiway",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxi_holding_position: None | TaxiHoldingPosition = field(
        default=None,
        metadata={
            "name": "TaxiHoldingPosition",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    guidance_line: None | GuidanceLine = field(
        default=None,
        metadata={
            "name": "GuidanceLine",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    seaplane_ramp_site: None | SeaplaneRampSite = field(
        default=None,
        metadata={
            "name": "SeaplaneRampSite",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    seaplane_landing_area: None | SeaplaneLandingArea = field(
        default=None,
        metadata={
            "name": "SeaplaneLandingArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    marking_buoy: None | MarkingBuoy = field(
        default=None,
        metadata={
            "name": "MarkingBuoy",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    floating_dock_site: None | FloatingDockSite = field(
        default=None,
        metadata={
            "name": "FloatingDockSite",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_visual_range: None | RunwayVisualRange = field(
        default=None,
        metadata={
            "name": "RunwayVisualRange",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_element: None | RunwayElement = field(
        default=None,
        metadata={
            "name": "RunwayElement",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_direction: None | RunwayDirection = field(
        default=None,
        metadata={
            "name": "RunwayDirection",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_centreline_point: None | RunwayCentrelinePoint = field(
        default=None,
        metadata={
            "name": "RunwayCentrelinePoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_blast_pad: None | RunwayBlastPad = field(
        default=None,
        metadata={
            "name": "RunwayBlastPad",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway: None | Runway = field(
        default=None,
        metadata={
            "name": "Runway",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    arresting_gear: None | ArrestingGear = field(
        default=None,
        metadata={
            "name": "ArrestingGear",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    touch_down_lift_off_marking: None | TouchDownLiftOffMarking = field(
        default=None,
        metadata={
            "name": "TouchDownLiftOffMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxiway_marking: None | TaxiwayMarking = field(
        default=None,
        metadata={
            "name": "TaxiwayMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxi_holding_position_marking: None | TaxiHoldingPositionMarking = field(
        default=None,
        metadata={
            "name": "TaxiHoldingPositionMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    stand_marking: None | StandMarking = field(
        default=None,
        metadata={
            "name": "StandMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_marking: None | RunwayMarking = field(
        default=None,
        metadata={
            "name": "RunwayMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    guidance_line_marking: None | GuidanceLineMarking = field(
        default=None,
        metadata={
            "name": "GuidanceLineMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    deicing_area_marking: None | DeicingAreaMarking = field(
        default=None,
        metadata={
            "name": "DeicingAreaMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    apron_marking: None | ApronMarking = field(
        default=None,
        metadata={
            "name": "ApronMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_protection_area_marking: None | AirportProtectionAreaMarking = field(
        default=None,
        metadata={
            "name": "AirportProtectionAreaMarking",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    visual_glide_slope_indicator: None | VisualGlideSlopeIndicator = field(
        default=None,
        metadata={
            "name": "VisualGlideSlopeIndicator",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    touch_down_lift_off_light_system: None | TouchDownLiftOffLightSystem = field(
        default=None,
        metadata={
            "name": "TouchDownLiftOffLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxiway_light_system: None | TaxiwayLightSystem = field(
        default=None,
        metadata={
            "name": "TaxiwayLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    taxi_holding_position_light_system: None | TaxiHoldingPositionLightSystem = field(
        default=None,
        metadata={
            "name": "TaxiHoldingPositionLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_protect_area_light_system: None | RunwayProtectAreaLightSystem = field(
        default=None,
        metadata={
            "name": "RunwayProtectAreaLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_direction_light_system: None | RunwayDirectionLightSystem = field(
        default=None,
        metadata={
            "name": "RunwayDirectionLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    guidance_line_light_system: None | GuidanceLineLightSystem = field(
        default=None,
        metadata={
            "name": "GuidanceLineLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    apron_light_system: None | ApronLightSystem = field(
        default=None,
        metadata={
            "name": "ApronLightSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    approach_lighting_system: None | ApproachLightingSystem = field(
        default=None,
        metadata={
            "name": "ApproachLightingSystem",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    touch_down_lift_off: None | TouchDownLiftOff = field(
        default=None,
        metadata={
            "name": "TouchDownLiftOff",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    road: None | Road = field(
        default=None,
        metadata={
            "name": "Road",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    passenger_loading_bridge: None | PassengerLoadingBridge = field(
        default=None,
        metadata={
            "name": "PassengerLoadingBridge",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    deicing_area: None | DeicingArea = field(
        default=None,
        metadata={
            "name": "DeicingArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    apron_element: None | ApronElement = field(
        default=None,
        metadata={
            "name": "ApronElement",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    apron: None | Apron = field(
        default=None,
        metadata={
            "name": "Apron",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    aircraft_stand: None | AircraftStand = field(
        default=None,
        metadata={
            "name": "AircraftStand",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    work_area: None | WorkArea = field(
        default=None,
        metadata={
            "name": "WorkArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    survey_control_point: None | SurveyControlPoint = field(
        default=None,
        metadata={
            "name": "SurveyControlPoint",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    non_movement_area: None | NonMovementArea = field(
        default=None,
        metadata={
            "name": "NonMovementArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    altimeter_source: None | AltimeterSource = field(
        default=None,
        metadata={
            "name": "AltimeterSource",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_hot_spot: None | AirportHotSpot = field(
        default=None,
        metadata={
            "name": "AirportHotSpot",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    runway_protect_area: None | RunwayProtectArea = field(
        default=None,
        metadata={
            "name": "RunwayProtectArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    touch_down_lift_off_safe_area: None | TouchDownLiftOffSafeArea = field(
        default=None,
        metadata={
            "name": "TouchDownLiftOffSafeArea",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_heliport_collocation: None | AirportHeliportCollocation = field(
        default=None,
        metadata={
            "name": "AirportHeliportCollocation",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    airport_heliport: None | AirportHeliport = field(
        default=None,
        metadata={
            "name": "AirportHeliport",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    aerial_refuelling: None | AerialRefuelling = field(
        default=None,
        metadata={
            "name": "AerialRefuelling",
            "type": "Element",
            "namespace": "http://www.aixm.aero/schema/5.1.1",
        },
    )
    feature_collection: None | FeatureCollection = field(
        default=None,
        metadata={
            "name": "FeatureCollection",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    directed_observation_at_distance: None | DirectedObservationAtDistance = field(
        default=None,
        metadata={
            "name": "DirectedObservationAtDistance",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    directed_observation: None | DirectedObservation = field(
        default=None,
        metadata={
            "name": "DirectedObservation",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    observation: None | Observation = field(
        default=None,
        metadata={
            "name": "Observation",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    rectified_grid_coverage: None | RectifiedGridCoverage = field(
        default=None,
        metadata={
            "name": "RectifiedGridCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    grid_coverage: None | GridCoverage = field(
        default=None,
        metadata={
            "name": "GridCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_solid_coverage: None | MultiSolidCoverage = field(
        default=None,
        metadata={
            "name": "MultiSolidCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_surface_coverage: None | MultiSurfaceCoverage = field(
        default=None,
        metadata={
            "name": "MultiSurfaceCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_curve_coverage: None | MultiCurveCoverage = field(
        default=None,
        metadata={
            "name": "MultiCurveCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    multi_point_coverage: None | MultiPointCoverage = field(
        default=None,
        metadata={
            "name": "MultiPointCoverage",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    dynamic_feature_collection: None | DynamicFeatureCollection = field(
        default=None,
        metadata={
            "name": "DynamicFeatureCollection",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    dynamic_feature: None | DynamicFeature = field(
        default=None,
        metadata={
            "name": "DynamicFeature",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    owns: bool = field(
        default=False,
        metadata={
            "type": "Attribute",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )
    remote_schema: None | str = field(
        default=None,
        metadata={
            "name": "remoteSchema",
            "type": "Attribute",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class LocationName(CodeType):
    """
    The gml:locationName property element is a convenience property where the text value describes the location of
    the feature.

    If the location names are selected from a controlled list, then the list shall be identified in the codeSpace
    attribute.
    """

    class Meta:
        name = "locationName"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class LocationReference(ReferenceType):
    """
    The gml:locationReference property element is a convenience property where the text value referenced by the
    xlink:href attribute describes the location of the feature.
    """

    class Meta:
        name = "locationReference"
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class EnvelopeWithTimePeriod(EnvelopeWithTimePeriodType):
    """
    gml:EnvelopeWithTimePeriod is provided for envelopes that include a temporal extent.

    It adds two time position properties, gml:beginPosition and gml:endPosition, which describe the extent of a
    time-envelope. Since gml:EnvelopeWithTimePeriod is assigned to the substitution group headed by gml:Envelope, it
    may be used whenever gml:Envelope is valid.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class BoundingShapeType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    elevated_envelope: None | ElevatedEnvelope = field(
        default=None,
        metadata={
            "name": "ElevatedEnvelope",
            "type": "Element",
            "namespace": "http://icao.int/iwxxm/2025-2",
        },
    )
    envelope_with_time_period: None | EnvelopeWithTimePeriod = field(
        default=None,
        metadata={
            "name": "EnvelopeWithTimePeriod",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    envelope: None | Envelope = field(
        default=None,
        metadata={
            "name": "Envelope",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    null: None | Null = field(
        default=None,
        metadata={
            "name": "Null",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "pattern": r"other:\w{2,}",
        },
    )


class BoundedBy(BoundingShapeType):
    """
    This property describes the minimum bounding box or rectangle that encloses the entire feature.
    """

    class Meta:
        name = "boundedBy"
        nillable = True
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)


class AbstractFeatureType(AbstractGmltype):
    """
    The basic feature model is given by the gml:AbstractFeatureType.

    The content model for gml:AbstractFeatureType adds two specific properties suitable for geographic features to
    the content model defined in gml:AbstractGMLType. The value of the gml:boundedBy property describes an envelope
    that encloses the entire feature instance, and is primarily useful for supporting rapid searching for features
    that occur in a particular location. The value of the gml:location property describes the extent, position or
    relative location of the feature.
    """

    model_config = ConfigDict(defer_build=True)
    bounded_by: None | BoundedBy = field(
        default=None,
        metadata={
            "name": "boundedBy",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
            "nillable": True,
        },
    )
    priority_location: None | PriorityLocation = field(
        default=None,
        metadata={
            "name": "priorityLocation",
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )
    location: None | Location = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.opengis.net/gml/3.2",
        },
    )


class AbstractFeature(AbstractFeatureType):
    """
    This abstract element serves as the head of a substitution group which may contain any elements whose content
    model is derived from gml:AbstractFeatureType.

    This may be used as a variable in the construction of content models. gml:AbstractFeature may be thought of as
    "anything that is a GML feature" and may be used to define variables or templates in which the value of a GML
    property is "any feature". This occurs in particular in a GML feature collection where the feature member
    properties contain one or multiple copies of gml:AbstractFeature respectively.
    """

    class Meta:
        namespace = "http://www.opengis.net/gml/3.2"

    model_config = ConfigDict(defer_build=True)
