"""This file was generated by xsdata, v26.2, on 2026-07-18 23:42:57

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

from ........xlink import (
    ActuateType,
    ShowType,
    TypeType,
)
from .....gml.pkg_3.pkg_2.pkg_1.basic_types import NilReasonEnumerationValue
from ..gco.basic_types import (
    BinaryPropertyType,
    CharacterStringPropertyType,
)
from ..gco.gco_base import AbstractObjectType
from .citation import CiCitationPropertyType

__NAMESPACE__ = "http://www.isotc211.org/2005/gmd"


class MdApplicationSchemaInformationType(AbstractObjectType):
    """
    Information about the application schema used to build the dataset.
    """

    class Meta:
        name = "MD_ApplicationSchemaInformation_Type"

    model_config = ConfigDict(defer_build=True)
    name: CiCitationPropertyType = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        }
    )
    schema_language: CharacterStringPropertyType = field(
        metadata={
            "name": "schemaLanguage",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        }
    )
    constraint_language: CharacterStringPropertyType = field(
        metadata={
            "name": "constraintLanguage",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        }
    )
    schema_ascii: None | CharacterStringPropertyType = field(
        default=None,
        metadata={
            "name": "schemaAscii",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        },
    )
    graphics_file: None | BinaryPropertyType = field(
        default=None,
        metadata={
            "name": "graphicsFile",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        },
    )
    software_development_file: None | BinaryPropertyType = field(
        default=None,
        metadata={
            "name": "softwareDevelopmentFile",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        },
    )
    software_development_file_format: None | CharacterStringPropertyType = field(
        default=None,
        metadata={
            "name": "softwareDevelopmentFileFormat",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        },
    )


class MdApplicationSchemaInformation(MdApplicationSchemaInformationType):
    class Meta:
        name = "MD_ApplicationSchemaInformation"
        namespace = "http://www.isotc211.org/2005/gmd"

    model_config = ConfigDict(defer_build=True)


class MdApplicationSchemaInformationPropertyType(BaseModel):
    class Meta:
        name = "MD_ApplicationSchemaInformation_PropertyType"

    model_config = ConfigDict(defer_build=True)
    md_application_schema_information: None | MdApplicationSchemaInformation = field(
        default=None,
        metadata={
            "name": "MD_ApplicationSchemaInformation",
            "type": "Element",
            "namespace": "http://www.isotc211.org/2005/gmd",
        },
    )
    type_value: TypeType = field(
        const=True,
        default=TypeType.SIMPLE,
        metadata={
            "name": "type",
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    href: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    role: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    arcrole: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
            "min_length": 1,
        },
    )
    title: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    show: None | ShowType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    actuate: None | ActuateType = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/1999/xlink",
        },
    )
    uuidref: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    nil_reason: None | str | NilReasonEnumerationValue = field(
        default=None,
        metadata={
            "name": "nilReason",
            "type": "Attribute",
            "namespace": "http://www.isotc211.org/2005/gco",
            "pattern": r"other:\w{2,}",
        },
    )
